<a href="https://colab.research.google.com/github/Segn11/datasciencebootcamp_project/blob/loan_defa0/loan_default_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [221]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [222]:
import zipfile
import os

zip_file_path = '/content/drive/MyDrive/data-science-nigeria-challenge-1-loan-default-prediction20250307-26022-im3qg9.zip'
extraction_path = '/content/loan_default_data/'

# Create the extraction directory if it doesn't exist
os.makedirs(extraction_path, exist_ok=True)

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f"Files extracted to: {extraction_path}")

# List the extracted files to verify
print("Extracted files:")
for root, dirs, files in os.walk(extraction_path):
    for file in files:
        print(os.path.join(root, file))

Files extracted to: /content/loan_default_data/
Extracted files:
/content/loan_default_data/testprevloans.zip
/content/loan_default_data/testperf.csv
/content/loan_default_data/SampleSubmission.csv
/content/loan_default_data/testdemographics.csv
/content/loan_default_data/manifest-155273bc0bf3f6c96da245fb19b9dc9320250307-26022-7yk61d.json
/content/loan_default_data/traindemographics.csv
/content/loan_default_data/trainprevloans.zip
/content/loan_default_data/trainperf.csv

In [223]:
import pandas as pd
import zipfile
import os

In [224]:
train0 = pd.read_csv('/content/loan_default_data/trainperf.csv')
train1 = pd.read_csv('/content/loan_default_data/traindemographics.csv')
train2 = pd.read_csv('/content/loan_default_data/trainprevloans.zip')

In [225]:
test0 = pd.read_csv('/content/loan_default_data/testperf.csv')
test1 = pd.read_csv('/content/loan_default_data/testprevloans.zip')
test2 = pd.read_csv('/content/loan_default_data/testdemographics.csv')

In [226]:
data_path = '/content/loan_default_data/'

# Load testdemographics.csv
test2 = pd.read_csv(os.path.join(data_path, 'testdemographics.csv'))
print("Test Demographics Data (Head):")
display(test2.head())
print("\nTest Demographics Info:")
test2.info()

Test Demographics Data (Head):

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858f305c8dd672015c93b1db645db4,1976-08-28 00:00:00.000000,Savings,5.296628,7.593965,Heritage Bank,NaN,Permanent,NaN
1,8a858f085a477386015a47fb049e49ca,1978-06-23 00:00:00.000000,Savings,3.294513,6.596602,UBA,NaN,Permanent,NaN
2,8a858e6f5cd5e874015cd6f5634c39ad,1984-04-04 00:00:00.000000,Savings,8.501912,7.729364,First Bank,NaN,Permanent,NaN
3,8a858e9d5bfd7037015bfdab79f61305,1983-05-28 00:00:00.000000,Savings,3.318904,6.681595,UBA,NaN,Permanent,NaN
4,8a858fde56eb02280156eb6dafc128ac,1982-03-29 00:00:00.000000,Savings,6.354624,4.949031,First Bank,NaN,Self-Employed,NaN

Test Demographics Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1487 entries, 0 to 1486
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1487 non-null   object
 1   birthdate                   1487 non-null   object
 2   bank_account_type           1487 non-null   object
 3   longitude_gps               1487 non-null   float64
 4   latitude_gps                1487 non-null   float64
 5   bank_name_clients           1487 non-null   object
 6   bank_branch_clients         14 non-null     object
 7   employment_status_clients   1270 non-null   object
 8   level_of_education_clients  210 non-null    object
dtypes: float64(2), object(7)
memory usage: 104.7+ KB

### Merging Test Data (Mirroring Train Data Process)

We will now combine `test0` (performance), `test1` (previous loans), and `test2` (demographics) into a single `test` dataframe, following the same logic as the training data preparation. This ensures consistency for your model.

In [227]:
print("Columns in test0:", test0.columns.tolist())
print("Columns in test2:", test2.columns.tolist())

# Step 1: Merge test0 (performance) and test2 (demographics)
test = pd.merge(test0, test2, on='customerid', how='left')

print("\nTest (merged test0 and test2) Head:")
display(test.head())
print("\nTest (merged test0 and test2) Info:")
test.info()

Columns in test0: ['customerid', 'systemloanid', 'loannumber', 'approveddate', 'creationdate', 'loanamount', 'totaldue', 'termdays', 'referredby']
Columns in test2: ['customerid', 'birthdate', 'bank_account_type', 'longitude_gps', 'latitude_gps', 'bank_name_clients', 'bank_branch_clients', 'employment_status_clients', 'level_of_education_clients']

Test (merged test0 and test2) Head:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858899538ddb8e015390510b321f08,301998974,4,40:48.0,39:35.0,10000,12250.0,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8a858959537a097401537a4e316e25f7,301963615,10,43:40.0,42:34.0,40000,44000.0,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,15:11.0,15:04.0,20000,24500.0,30,NaN,1981-09-05 00:00:00.000000,Savings,3.227945,6.586668,UBA,NaN,Permanent,NaN
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,00:54.0,00:49.0,30000,34500.0,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8a858e225a28c713015a30db5c48383d,301959177,4,04:33.0,04:27.0,20000,24500.0,30,NaN,1975-08-25 00:00:00.000000,Savings,5.248368,13.059864,UBA,NaN,Permanent,NaN

Test (merged test0 and test2) Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                1450 non-null   object
 4   creationdate                1450 non-null   object
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   birthdate                   385 non-null    object
 10  bank_account_type           385 non-null    object
 11  longitude_gps               385 non-null    float64
 12  latitude_gps                385 non-null    float64
 13  bank_name_clients           385 non-null    object
 14  bank_branch_clients         4 non-null      object
 15  employment_status_clients   332 non-null    object
 16  level_of_education_clients  47 non-null     object
dtypes: float64(3), int64(4), object(10)
memory usage: 192.7+ KB

Next, we'll aggregate `test1` (previous loans) data by `customerid` to create summary statistics, just as we did for `train2`.

In [228]:
print("Columns in test1:", test1.columns.tolist())

# Aggregate test1 (previous loans) by customerid
test_prevloans_agg = test1.groupby('customerid').agg(
    num_prev_loans=('systemloanid', 'count'),
    total_prev_loanamount=('loanamount', 'sum'),
    avg_prev_loanamount=('loanamount', 'mean'),
    total_prev_totaldue=('totaldue', 'sum'),
    avg_prev_totaldue=('totaldue', 'mean'),
    avg_prev_termdays=('termdays', 'mean')
).reset_index()

print("\nAggregated Test Previous Loans Data (Head):")
display(test_prevloans_agg.head())
print("\nAggregated Test Previous Loans Data Info:")
test_prevloans_agg.info()

Columns in test1: ['customerid', 'systemloanid', 'loannumber', 'approveddate', 'creationdate', 'loanamount', 'totaldue', 'termdays', 'closeddate', 'referredby', 'firstduedate', 'firstrepaiddate']

Aggregated Test Previous Loans Data (Head):

,customerid,num_prev_loans,total_prev_loanamount,avg_prev_loanamount,total_prev_totaldue,avg_prev_totaldue,avg_prev_termdays
0,8a28afc7474813a40147639ec637156b,10,178000.0,17800.000000,210900.0,21090.000000,31.5
1,8a3735d5518aba7301518ac34413010d,6,70000.0,11666.666667,88000.0,14666.666667,27.5
2,8a76e7d443e6e97c0143ed099d102b1d,2,20000.0,10000.000000,23000.0,11500.000000,15.0
3,8a818823525dceef01525deda2480384,9,170000.0,18888.888889,209975.0,23330.555556,40.0
4,8a818926522ea5ef01523aff15c37482,2,20000.0,10000.000000,26000.0,13000.000000,30.0

Aggregated Test Previous Loans Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1442 entries, 0 to 1441
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customerid             1442 non-null   object
 1   num_prev_loans         1442 non-null   int64
 2   total_prev_loanamount  1442 non-null   float64
 3   avg_prev_loanamount    1442 non-null   float64
 4   total_prev_totaldue    1442 non-null   float64
 5   avg_prev_totaldue      1442 non-null   float64
 6   avg_prev_termdays      1442 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 79.0+ KB

Now, we merge the aggregated previous loans data (`test_prevloans_agg`) with the combined `test` dataset.

In [229]:
# Merge the aggregated previous loans with the main test dataframe
test = pd.merge(test, test_prevloans_agg, on='customerid', how='left')

print("\nFinal Merged Test Data (Head - after prev loans merge):")
display(test.head())
print("\nFinal Merged Test Data Info - after prev loans merge:")
test.info()
print("\nShape of the final test dataset:", test.shape)

Final Merged Test Data (Head - after prev loans merge):

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,birthdate,...,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,num_prev_loans,total_prev_loanamount,avg_prev_loanamount,total_prev_totaldue,avg_prev_totaldue,avg_prev_termdays
0,8a858899538ddb8e015390510b321f08,301998974,4,40:48.0,39:35.0,10000,12250.0,30,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,26000.0,8666.666667,32900.0,10966.666667,25.000000
1,8a858959537a097401537a4e316e25f7,301963615,10,43:40.0,42:34.0,40000,44000.0,30,NaN,NaN,...,NaN,NaN,NaN,NaN,9.0,215000.0,23888.888889,248400.0,27600.000000,31.666667
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,15:11.0,15:04.0,20000,24500.0,30,NaN,1981-09-05 00:00:00.000000,...,UBA,NaN,Permanent,NaN,5.0,65000.0,13000.000000,79675.0,15935.000000,27.000000
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,00:54.0,00:49.0,30000,34500.0,30,NaN,NaN,...,NaN,NaN,NaN,NaN,7.0,120000.0,17142.857143,135400.0,19342.857143,17.142857
4,8a858e225a28c713015a30db5c48383d,301959177,4,04:33.0,04:27.0,20000,24500.0,30,NaN,1975-08-25 00:00:00.000000,...,UBA,NaN,Permanent,NaN,3.0,30000.0,10000.000000,37500.0,12500.000000,25.000000

Final Merged Test Data Info - after prev loans merge:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                1450 non-null   object
 4   creationdate                1450 non-null   object
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   birthdate                   385 non-null    object
 10  bank_account_type           385 non-null    object
 11  longitude_gps               385 non-null    float64
 12  latitude_gps                385 non-null    float64
 13  bank_name_clients           385 non-null    object
 14  bank_branch_clients         4 non-null      object
 15  employment_status_clients   332 non-null    object
 16  level_of_education_clients  47 non-null     object
 17  num_prev_loans              1442 non-null   float64
 18  total_prev_loanamount       1442 non-null   float64
 19  avg_prev_loanamount         1442 non-null   float64
 20  total_prev_totaldue         1442 non-null   float64
 21  avg_prev_totaldue           1442 non-null   float64
 22  avg_prev_termdays           1442 non-null   float64
dtypes: float64(9), int64(4), object(10)
memory usage: 260.7+ KB

Shape of the final test dataset: (1450, 23)

In [230]:
print("Columns in train0:", train0.columns.tolist())
print("Columns in train1:", train1.columns.tolist())
print("Columns in train2:", train2.columns.tolist())

# Merge train0 (performance) and train1 (demographics) first
train = pd.merge(train0, train1, on='customerid', how='left')

print("\nTrain (merged train0 and train1) Head:")
display(train.head())
print("\nTrain (merged train0 and train1) Info:")
train.info()

Columns in train0: ['customerid', 'systemloanid', 'loannumber', 'approveddate', 'creationdate', 'loanamount', 'totaldue', 'termdays', 'referredby', 'good_bad_flag']
Columns in train1: ['customerid', 'birthdate', 'bank_account_type', 'longitude_gps', 'latitude_gps', 'bank_name_clients', 'bank_branch_clients', 'employment_status_clients', 'level_of_education_clients']
Columns in train2: ['customerid', 'systemloanid', 'loannumber', 'approveddate', 'creationdate', 'loanamount', 'totaldue', 'termdays', 'closeddate', 'referredby', 'firstduedate', 'firstrepaiddate']

Train (merged train0 and train1) Head:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,NaN,Good,1972-01-15 00:00:00.000000,Other,3.432010,6.433055,Diamond Bank,NaN,Permanent,Post-Graduate
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,NaN,Good,1985-08-23 00:00:00.000000,Savings,3.885298,7.320700,GT Bank,"DUGBE,IBADAN",Permanent,Graduate
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,NaN,Good,1984-09-18 00:00:00.000000,Other,11.139350,10.292041,EcoBank,NaN,Permanent,NaN
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,NaN,Good,1977-10-10 00:00:00.000000,Savings,3.985770,7.491708,First Bank,NaN,Permanent,NaN
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,NaN,Good,1986-09-07 00:00:00.000000,Other,7.457913,9.076574,GT Bank,NaN,Permanent,Primary

Train (merged train0 and train1) Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   object
 4   creationdate                4376 non-null   object
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   object
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
dtypes: float64(4), int64(3), object(11)
memory usage: 615.5+ KB

Now, let's aggregate `train2` (previous loans) data by `customerid` to avoid duplicating rows when merging. We'll calculate some summary statistics for previous loans.

In [231]:
# Aggregate train2 (previous loans) by customerid
prevloans_agg = train2.groupby('customerid').agg(
    num_prev_loans=('systemloanid', 'count'),
    total_prev_loanamount=('loanamount', 'sum'),
    avg_prev_loanamount=('loanamount', 'mean'),
    total_prev_totaldue=('totaldue', 'sum'),
    avg_prev_totaldue=('totaldue', 'mean'),
    avg_prev_termdays=('termdays', 'mean')
).reset_index()

print("\nAggregated Previous Loans Data (Head):")
display(prevloans_agg.head())
print("\nAggregated Previous Loans Data Info:")
prevloans_agg.info()

Aggregated Previous Loans Data (Head):

,customerid,num_prev_loans,total_prev_loanamount,avg_prev_loanamount,total_prev_totaldue,avg_prev_totaldue,avg_prev_termdays
0,8a1088a0484472eb01484669e3ce4e0b,1,10000.0,10000.000000,11500.0,11500.000000,15.000000
1,8a1a1e7e4f707f8b014f797718316cad,4,70000.0,17500.000000,89500.0,22375.000000,37.500000
2,8a1a32fc49b632520149c3b8fdf85139,7,90000.0,12857.142857,106500.0,15214.285714,19.285714
3,8a1eb5ba49a682300149c3c068b806c7,8,130000.0,16250.000000,162400.0,20300.000000,33.750000
4,8a1edbf14734127f0147356fdb1b1eb2,2,20000.0,10000.000000,24500.0,12250.000000,22.500000

Aggregated Previous Loans Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4359 entries, 0 to 4358
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customerid             4359 non-null   object
 1   num_prev_loans         4359 non-null   int64
 2   total_prev_loanamount  4359 non-null   float64
 3   avg_prev_loanamount    4359 non-null   float64
 4   total_prev_totaldue    4359 non-null   float64
 5   avg_prev_totaldue      4359 non-null   float64
 6   avg_prev_termdays      4359 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 238.5+ KB

Finally, merge the aggregated previous loans data (`prevloans_agg`) with the combined `train` dataset.

In [232]:
# Merge the aggregated previous loans with the main train dataframe
train = pd.merge(train, prevloans_agg, on='customerid', how='left')

print("\nFinal Merged Train Data (Head):")
display(train.head())
print("\nFinal Merged Train Data Info:")
train.info()
print("\nShape of the final train dataset:", train.shape)

Final Merged Train Data (Head):

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,...,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,num_prev_loans,total_prev_loanamount,avg_prev_loanamount,total_prev_totaldue,avg_prev_totaldue,avg_prev_termdays
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,NaN,Good,...,Diamond Bank,NaN,Permanent,Post-Graduate,11.0,200000.0,18181.818182,242900.0,22081.818182,30.0
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,NaN,Good,...,GT Bank,"DUGBE,IBADAN",Permanent,Graduate,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,NaN,Good,...,EcoBank,NaN,Permanent,NaN,6.0,60000.0,10000.000000,70500.0,11750.000000,17.5
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,NaN,Good,...,First Bank,NaN,Permanent,NaN,2.0,20000.0,10000.000000,24500.0,12250.000000,22.5
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,NaN,Good,...,GT Bank,NaN,Permanent,Primary,8.0,150000.0,18750.000000,188400.0,23550.000000,37.5

Final Merged Train Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   object
 4   creationdate                4376 non-null   object
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   object
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
 18  num_prev_loans              4367 non-null   float64
 19  total_prev_loanamount       4367 non-null   float64
 20  avg_prev_loanamount         4367 non-null   float64
 21  total_prev_totaldue         4367 non-null   float64
 22  avg_prev_totaldue           4367 non-null   float64
 23  avg_prev_termdays           4367 non-null   float64
dtypes: float64(10), int64(3), object(11)
memory usage: 820.6+ KB

Shape of the final train dataset: (4376, 24)

In [233]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   object
 4   creationdate                4376 non-null   object
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   object
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
 18  num_prev_loans              4367 non-null   float64
 19  total_prev_loanamount       4367 non-null   float64
 20  avg_prev_loanamount         4367 non-null   float64
 21  total_prev_totaldue         4367 non-null   float64
 22  avg_prev_totaldue           4367 non-null   float64
 23  avg_prev_termdays           4367 non-null   float64
dtypes: float64(10), int64(3), object(11)
memory usage: 820.6+ KB

In [234]:
sampsub = pd.read_csv('/content/loan_default_data/SampleSubmission.csv')
#sampsub.head()

In [235]:
test_id = test.drop(['customerid'], axis=1)
train_id = train.drop(['customerid', 'systemloanid'], axis=1)

test_is = test.drop(['systemloanid'], axis=1)

In [236]:
cat_cols = train.select_dtypes(include="object").columns
cat_cols = list(cat_cols)
print(cat_cols)

['customerid', 'approveddate', 'creationdate', 'referredby', 'good_bad_flag', 'birthdate', 'bank_account_type', 'bank_name_clients', 'bank_branch_clients', 'employment_status_clients', 'level_of_education_clients']

In [237]:
num_cols = test.select_dtypes(include="number").columns
num_cols = list(num_cols)
print(num_cols)

['systemloanid', 'loannumber', 'loanamount', 'totaldue', 'termdays', 'longitude_gps', 'latitude_gps', 'num_prev_loans', 'total_prev_loanamount', 'avg_prev_loanamount', 'total_prev_totaldue', 'avg_prev_totaldue', 'avg_prev_termdays']

In [238]:
# Select numeric columns dynamically
num_cols_train = train.select_dtypes(include=['int64', 'float64']).columns
num_cols_test = test.select_dtypes(include=['int64', 'float64']).columns

# Select categorical columns dynamically
cat_cols_train = train.select_dtypes(include='object').columns
cat_cols_test = test.select_dtypes(include='object').columns

# Fill missing values
train[num_cols_train] = train[num_cols_train].fillna(0)
test[num_cols_test] = test[num_cols_test].fillna(0)

train[cat_cols_train] = train[cat_cols_train].fillna('unknown')
test[cat_cols_test] = test[cat_cols_test].fillna('unknown')

In [239]:
train.isna().sum()

customerid                    0
systemloanid                  0
loannumber                    0
approveddate                  0
creationdate                  0
loanamount                    0
totaldue                      0
termdays                      0
referredby                    0
good_bad_flag                 0
birthdate                     0
bank_account_type             0
longitude_gps                 0
latitude_gps                  0
bank_name_clients             0
bank_branch_clients           0
employment_status_clients     0
level_of_education_clients    0
num_prev_loans                0
total_prev_loanamount         0
avg_prev_loanamount           0
total_prev_totaldue           0
avg_prev_totaldue             0
avg_prev_termdays             0
dtype: int64

In [240]:
# Convert to datetime
train['approveddate'] = pd.to_datetime(train['approveddate'], errors='coerce')
train['creationdate'] = pd.to_datetime(train['creationdate'], errors='coerce')

test['approveddate'] = pd.to_datetime(test['approveddate'], errors='coerce')
test['creationdate'] = pd.to_datetime(test['creationdate'], errors='coerce')

/tmp/ipython-input-1897446360.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test['approveddate'] = pd.to_datetime(test['approveddate'], errors='coerce')
/tmp/ipython-input-1897446360.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test['creationdate'] = pd.to_datetime(test['creationdate'], errors='coerce')

In [241]:
# Year, month, day, weekday
for df in [train, test]:
    df['approved_year'] = df['approveddate'].dt.year
    df['approved_month'] = df['approveddate'].dt.month
    df['approved_day'] = df['approveddate'].dt.day
    df['approved_weekday'] = df['approveddate'].dt.weekday  # 0=Monday, 6=Sunday

    # Loan age in days
    df['loan_age_days'] = (df['approveddate'] - df['creationdate']).dt.days

In [242]:
train = train.drop(['approveddate', 'creationdate'], axis=1)
test = test.drop(['approveddate', 'creationdate'], axis=1)

In [243]:
# Select numeric columns dynamically
num_cols_train = train.select_dtypes(include=['int64', 'float64']).columns
num_cols_test = test.select_dtypes(include=['int64', 'float64']).columns

# Select categorical columns dynamically
cat_cols_train = train.select_dtypes(include='object').columns
cat_cols_test = test.select_dtypes(include='object').columns

# Fill missing values
train[num_cols_train] = train[num_cols_train].fillna(0)
test[num_cols_test] = test[num_cols_test].fillna(0)

train[cat_cols_train] = train[cat_cols_train].fillna('unknown')
test[cat_cols_test] = test[cat_cols_test].fillna('unknown')

In [244]:
today = pd.Timestamp.today()
train['age'] = (today - pd.to_datetime(train['birthdate'], errors='coerce')).dt.days // 365
test['age'] = (today - pd.to_datetime(test['birthdate'], errors='coerce')).dt.days // 365

/tmp/ipython-input-3930086714.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test['age'] = (today - pd.to_datetime(test['birthdate'], errors='coerce')).dt.days // 365

In [245]:
train.drop('birthdate', axis=1, inplace=True)
test.drop('birthdate', axis=1, inplace=True)

In [246]:
# Select numeric columns dynamically
num_cols_train = train.select_dtypes(include=['int64', 'float64']).columns
num_cols_test = test.select_dtypes(include=['int64', 'float64']).columns

# Select categorical columns dynamically
cat_cols_train = train.select_dtypes(include='object').columns
cat_cols_test = test.select_dtypes(include='object').columns

# Fill missing values
train[num_cols_train] = train[num_cols_train].fillna(0)
test[num_cols_test] = test[num_cols_test].fillna(0)

train[cat_cols_train] = train[cat_cols_train].fillna('unknown')
test[cat_cols_test] = test[cat_cols_test].fillna('unknown')

In [247]:
test_ids = test['customerid'].copy()

In [248]:
# Target variable
# Check if 'good_bad_flag' exists before extracting and converting
if 'good_bad_flag' in train.columns:
    y = train['good_bad_flag'].map({'Bad': 0, 'Good': 1})
    # Drop 'good_bad_flag' from train now that y is set
    train = train.drop('good_bad_flag', axis=1)
else:
    print("Warning: 'good_bad_flag' column not found in 'train' DataFrame. Assuming 'y' is already set.")

# Drop other ID columns from train
cols_to_drop_train_ids = ['customerid', 'systemloanid']
for col in cols_to_drop_train_ids:
    if col in train.columns:
        train = train.drop(col, axis=1)

# Drop ID columns from test
cols_to_drop_test_ids = ['customerid', 'systemloanid']
for col in cols_to_drop_test_ids:
    if col in test.columns:
        test = test.drop(col, axis=1)

In [249]:
# Define the mapping for education
edu_map = {
    "No formal education": 0,
    "Primary education": 1,
    "Secondary education": 2,
    "Tertiary education": 3
}

# Encode train
train["education_num"] = train["level_of_education_clients"].map(edu_map).fillna(-1).astype(int)

# Encode test
test["education_num"] = test["level_of_education_clients"].map(edu_map).fillna(-1).astype(int)

# Drop the original categorical column
train = train.drop("level_of_education_clients", axis=1)
test = test.drop("level_of_education_clients", axis=1)

In [250]:
#train = train.drop(['customerid', 'systemloanid'], axis=1)
#test = test.drop(['customerid', 'systemloanid'], axis=1)

In [251]:
from sklearn.preprocessing import OrdinalEncoder

# --- Ordinal features ---
ordinal_cols = ['education_num', 'employment_status_clients']  # make sure 'education_num' already exists
train[ordinal_cols] = train[ordinal_cols].fillna(-1)  # handle missing values
test[ordinal_cols] = test[ordinal_cols].fillna(-1)

ord_enc = OrdinalEncoder()
train[ordinal_cols] = ord_enc.fit_transform(train[ordinal_cols])
test[ordinal_cols] = ord_enc.transform(test[ordinal_cols])

# --- One-hot features ---
onehot_cols = ['bank_account_type', 'bank_name_clients', 'bank_branch_clients', 'referredby']

# Fill missing values
train[onehot_cols] = train[onehot_cols].fillna('unknown')
test[onehot_cols] = test[onehot_cols].fillna('unknown')

# One-hot encoding
train = pd.get_dummies(train, columns=onehot_cols, prefix_sep="_")
test = pd.get_dummies(test, columns=onehot_cols, prefix_sep="_")

# --- Align train/test columns ---
train, test = train.align(test, join='left', axis=1, fill_value=0)

In [252]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Columns: 597 entries, loannumber to referredby_unknown
dtypes: bool(577), float64(13), int32(4), int64(3)
memory usage: 3.0 MB

In [253]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Columns: 597 entries, loannumber to referredby_unknown
dtypes: bool(66), float64(17), int64(514)
memory usage: 6.0 MB

In [254]:
cat_cols = train.select_dtypes(include="object").columns
cat_cols = list(cat_cols)
print(cat_cols)

[]

In [255]:
from sklearn.model_selection import train_test_split
print("Imported train_test_split from sklearn.model_selection")

Imported train_test_split from sklearn.model_selection

**Reasoning**:
Now that `train_test_split` is imported, I will use it to split the `train` DataFrame and `y` Series into training and validation sets as instructed, using the specified `test_size`, `random_state`, and `stratify` parameters.

In [256]:
X_train, X_val, y_train, y_val = train_test_split(train, y, test_size=0.2, random_state=42, stratify=y)

print("Training and validation sets created successfully.")
print(f"X_train shape: {X_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_val shape: {y_val.shape}")

Training and validation sets created successfully.
X_train shape: (3500, 597)
X_val shape: (876, 597)
y_train shape: (3500,)
y_val shape: (876,)

In [257]:
from sklearn.linear_model import LogisticRegression
print("LogisticRegression imported successfully.")

LogisticRegression imported successfully.

**Reasoning**:
Now that `LogisticRegression` is imported, I will initialize the model with specified parameters and then train it using the `X_train` and `y_train` datasets, as per the instructions.

In [258]:
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)
print("Logistic Regression model initialized and trained successfully.")

Logistic Regression model initialized and trained successfully.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

**Reasoning**:
The previous Logistic Regression model training resulted in a `ConvergenceWarning`, indicating that the optimizer failed to converge. Scaling the data is a common and effective technique to help linear models like Logistic Regression converge more efficiently. I will scale the `X_train` and `X_val` data using `StandardScaler` before re-training the model.

In [259]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Fit the scaler on X_train and transform both X_train and X_val
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

# Initialize and train the Logistic Regression model with scaled data
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)
print("Logistic Regression model initialized and trained successfully with scaled data.")

Logistic Regression model initialized and trained successfully with scaled data.

In [260]:
y_pred = model.predict(X_val_scaled)
y_prob = model.predict_proba(X_val_scaled)[:, 1]
print("Predictions and probability scores calculated.")

Predictions and probability scores calculated.

In [261]:
from sklearn.metrics import accuracy_score
print("accuracy_score imported successfully.")

accuracy_score imported successfully.

In [262]:
accuracy = accuracy_score(y_val, y_pred)
error_rate = (1 - accuracy) * 100

print(f"Accuracy Score: {accuracy:.4f}")
print(f"Error Rate: {error_rate:.2f}%")

Accuracy Score: 0.7808
Error Rate: 21.92%

In [263]:
sampsub = pd.read_csv('/content/loan_default_data/SampleSubmission.csv')
sampsub.head()

                         customerid  Good_Bad_flag
0  8a28afc7474813a40147639ec637156b              1
1  8a3735d5518aba7301518ac34413010d              1
2  8a76e7d443e6e97c0143ed099d102b1d              1
3  8a818823525dceef01525deda2480384              1
4  8a818926522ea5ef01523aff15c37482              1

## Predict on Test Data

### Subtask:
Use the trained logistic regression model to make predictions on the preprocessed test dataset.

In [264]:
# Scale the test data using the same scaler fitted on the training data
X_test_scaled = scaler.transform(test)

# Make predictions on the scaled test data
y_test_pred = model.predict(X_test_scaled)
y_test_prob = model.predict_proba(X_test_scaled)[:, 1]

print("Predictions on the test set completed successfully.")
print("Sample of predicted classes (first 10):", y_test_pred[:10])
print("Sample of predicted probabilities for positive class (first 10):", y_test_prob[:10])

Predictions on the test set completed successfully.
Sample of predicted classes (first 10): [1 1 1 1 1 1 1 1 1 1]
Sample of predicted probabilities for positive class (first 10): [0.71330113 0.92546584 0.84479131 0.88141762 0.82263598 0.87072297
 0.79626317 0.7617521  0.81287125 0.97534939]

In [266]:
submission = pd.DataFrame({
    'customerID': test_ids,
    'Good_Bad_flag': y_test_pred
})

submission.to_csv("submission.csv", index=False)




print("Submission preview:")
print(submission.head(10))

Submission preview:
                         customerID  Good_Bad_flag
0  8a858899538ddb8e015390510b321f08              1
1  8a858959537a097401537a4e316e25f7              1
2  8a8589c253ace09b0153af6ba58f1f31              1
3  8a858e095aae82b7015aae86ca1e030b              1
4  8a858e225a28c713015a30db5c48383d              1
5  8a858e42570314e001570584d48641dc              1
6  8a858e675c3fe0a1015c44ba8a037fee              1
7  8a858e705668e16701568d358c6579da              1
8  8a858e945bb0014b015bb526a9584a2d              1
9  8a858eba5b681df4015b7c3d810c05ff              1