<a href="https://colab.research.google.com/github/Segn11/datasciencebootcamp_project/blob/srypto_pred2/loan_default_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import zipfile
import os

zip_file_path = '/content/drive/MyDrive/data-science-nigeria-challenge-1-loan-default-prediction20250307-26022-im3qg9.zip'
extraction_path = '/content/loan_default_data/'

# Create the extraction directory if it doesn't exist
os.makedirs(extraction_path, exist_ok=True)

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f"Files extracted to: {extraction_path}")

# List the extracted files to verify
print("Extracted files:")
for root, dirs, files in os.walk(extraction_path):
    for file in files:
        print(os.path.join(root, file))

Files extracted to: /content/loan_default_data/
Extracted files:
/content/loan_default_data/testperf.csv
/content/loan_default_data/testprevloans.zip
/content/loan_default_data/traindemographics.csv
/content/loan_default_data/SampleSubmission.csv
/content/loan_default_data/trainperf.csv
/content/loan_default_data/manifest-155273bc0bf3f6c96da245fb19b9dc9320250307-26022-7yk61d.json
/content/loan_default_data/testdemographics.csv
/content/loan_default_data/trainprevloans.zip

In [3]:
import pandas as pd
import zipfile
import os

In [4]:
train0 = pd.read_csv('/content/loan_default_data/trainperf.csv')
train1 = pd.read_csv('/content/loan_default_data/traindemographics.csv')
train2 = pd.read_csv('/content/loan_default_data/trainprevloans.zip')

In [5]:
train0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4368 entries, 0 to 4367
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     4368 non-null   object
 1   systemloanid   4368 non-null   int64
 2   loannumber     4368 non-null   int64
 3   approveddate   4368 non-null   object
 4   creationdate   4368 non-null   object
 5   loanamount     4368 non-null   float64
 6   totaldue       4368 non-null   float64
 7   termdays       4368 non-null   int64
 8   referredby     587 non-null    object
 9   good_bad_flag  4368 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 341.4+ KB

In [6]:
test0 = pd.read_csv('/content/loan_default_data/testperf.csv')
test1 = pd.read_csv('/content/loan_default_data/testprevloans.zip')
test2 = pd.read_csv('/content/loan_default_data/testdemographics.csv')

In [7]:
data_path = '/content/loan_default_data/'

# Load testdemographics.csv
test2 = pd.read_csv(os.path.join(data_path, 'testdemographics.csv'))
print("Test Demographics Data (Head):")
display(test2.head())
print("\nTest Demographics Info:")
test2.info()

Test Demographics Data (Head):

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858f305c8dd672015c93b1db645db4,1976-08-28 00:00:00.000000,Savings,5.296628,7.593965,Heritage Bank,NaN,Permanent,NaN
1,8a858f085a477386015a47fb049e49ca,1978-06-23 00:00:00.000000,Savings,3.294513,6.596602,UBA,NaN,Permanent,NaN
2,8a858e6f5cd5e874015cd6f5634c39ad,1984-04-04 00:00:00.000000,Savings,8.501912,7.729364,First Bank,NaN,Permanent,NaN
3,8a858e9d5bfd7037015bfdab79f61305,1983-05-28 00:00:00.000000,Savings,3.318904,6.681595,UBA,NaN,Permanent,NaN
4,8a858fde56eb02280156eb6dafc128ac,1982-03-29 00:00:00.000000,Savings,6.354624,4.949031,First Bank,NaN,Self-Employed,NaN

Test Demographics Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1487 entries, 0 to 1486
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1487 non-null   object
 1   birthdate                   1487 non-null   object
 2   bank_account_type           1487 non-null   object
 3   longitude_gps               1487 non-null   float64
 4   latitude_gps                1487 non-null   float64
 5   bank_name_clients           1487 non-null   object
 6   bank_branch_clients         14 non-null     object
 7   employment_status_clients   1270 non-null   object
 8   level_of_education_clients  210 non-null    object
dtypes: float64(2), object(7)
memory usage: 104.7+ KB

Now, let's merge the `test2` (demographics) with the existing `test` dataframe.

In [8]:
# First, ensure test_prevloans_agg is created by aggregating test1
test_prevloans_agg = test1.groupby('customerid').agg(
    num_prev_loans=('systemloanid', 'count'),
    total_prev_loanamount=('loanamount', 'sum'),
    avg_prev_loanamount=('loanamount', 'mean'),
    total_prev_totaldue=('totaldue', 'sum'),
    avg_prev_totaldue=('totaldue', 'mean'),
    avg_prev_termdays=('termdays', 'mean')
).reset_index()

# Then, create the initial 'test' dataframe by merging test0 with test_prevloans_agg
test = pd.merge(test0, test_prevloans_agg, on='customerid', how='left')

# Now, merge this 'test' dataframe with 'test2' (demographics)
# We'll use 'customerid' as the common key
test = pd.merge(test, test2, on='customerid', how='left')

print("\nFinal Merged Test Data (Head - with demographics):")
display(test.head())
print("\nFinal Merged Test Data Info - with demographics:")
test.info()
print("\nShape of the final test dataset (with demographics):", test.shape)

Final Merged Test Data (Head - with demographics):

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,num_prev_loans,...,avg_prev_totaldue,avg_prev_termdays,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858899538ddb8e015390510b321f08,301998974,4,40:48.0,39:35.0,10000,12250.0,30,NaN,3.0,...,10966.666667,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8a858959537a097401537a4e316e25f7,301963615,10,43:40.0,42:34.0,40000,44000.0,30,NaN,9.0,...,27600.000000,31.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,15:11.0,15:04.0,20000,24500.0,30,NaN,5.0,...,15935.000000,27.000000,1981-09-05 00:00:00.000000,Savings,3.227945,6.586668,UBA,NaN,Permanent,NaN
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,00:54.0,00:49.0,30000,34500.0,30,NaN,7.0,...,19342.857143,17.142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8a858e225a28c713015a30db5c48383d,301959177,4,04:33.0,04:27.0,20000,24500.0,30,NaN,3.0,...,12500.000000,25.000000,1975-08-25 00:00:00.000000,Savings,5.248368,13.059864,UBA,NaN,Permanent,NaN

Final Merged Test Data Info - with demographics:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                1450 non-null   object
 4   creationdate                1450 non-null   object
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   num_prev_loans              1442 non-null   float64
 10  total_prev_loanamount       1442 non-null   float64
 11  avg_prev_loanamount         1442 non-null   float64
 12  total_prev_totaldue         1442 non-null   float64
 13  avg_prev_totaldue           1442 non-null   float64
 14  avg_prev_termdays           1442 non-null   float64
 15  birthdate                   385 non-null    object
 16  bank_account_type           385 non-null    object
 17  longitude_gps               385 non-null    float64
 18  latitude_gps                385 non-null    float64
 19  bank_name_clients           385 non-null    object
 20  bank_branch_clients         4 non-null      object
 21  employment_status_clients   332 non-null    object
 22  level_of_education_clients  47 non-null     object
dtypes: float64(9), int64(4), object(10)
memory usage: 260.7+ KB

Shape of the final test dataset (with demographics): (1450, 23)

In [9]:
import zipfile
import os
import pandas as pd

In [10]:
print("Columns in train0:", train0.columns.tolist())
print("Columns in train1:", train1.columns.tolist())
print("Columns in train2:", train2.columns.tolist())

# Merge train0 (performance) and train1 (demographics) first
train = pd.merge(train0, train1, on='customerid', how='left')

print("\nTrain (merged train0 and train1) Head:")
display(train.head())
print("\nTrain (merged train0 and train1) Info:")
train.info()

Columns in train0: ['customerid', 'systemloanid', 'loannumber', 'approveddate', 'creationdate', 'loanamount', 'totaldue', 'termdays', 'referredby', 'good_bad_flag']
Columns in train1: ['customerid', 'birthdate', 'bank_account_type', 'longitude_gps', 'latitude_gps', 'bank_name_clients', 'bank_branch_clients', 'employment_status_clients', 'level_of_education_clients']
Columns in train2: ['customerid', 'systemloanid', 'loannumber', 'approveddate', 'creationdate', 'loanamount', 'totaldue', 'termdays', 'closeddate', 'referredby', 'firstduedate', 'firstrepaiddate']

Train (merged train0 and train1) Head:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,NaN,Good,1972-01-15 00:00:00.000000,Other,3.432010,6.433055,Diamond Bank,NaN,Permanent,Post-Graduate
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,NaN,Good,1985-08-23 00:00:00.000000,Savings,3.885298,7.320700,GT Bank,"DUGBE,IBADAN",Permanent,Graduate
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,NaN,Good,1984-09-18 00:00:00.000000,Other,11.139350,10.292041,EcoBank,NaN,Permanent,NaN
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,NaN,Good,1977-10-10 00:00:00.000000,Savings,3.985770,7.491708,First Bank,NaN,Permanent,NaN
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,NaN,Good,1986-09-07 00:00:00.000000,Other,7.457913,9.076574,GT Bank,NaN,Permanent,Primary

Train (merged train0 and train1) Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   object
 4   creationdate                4376 non-null   object
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   object
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
dtypes: float64(4), int64(3), object(11)
memory usage: 615.5+ KB

Now, let's aggregate `train2` (previous loans) data by `customerid` to avoid duplicating rows when merging. We'll calculate some summary statistics for previous loans.

In [11]:
# Aggregate train2 (previous loans) by customerid
prevloans_agg = train2.groupby('customerid').agg(
    num_prev_loans=('systemloanid', 'count'),
    total_prev_loanamount=('loanamount', 'sum'),
    avg_prev_loanamount=('loanamount', 'mean'),
    total_prev_totaldue=('totaldue', 'sum'),
    avg_prev_totaldue=('totaldue', 'mean'),
    avg_prev_termdays=('termdays', 'mean')
).reset_index()

print("\nAggregated Previous Loans Data (Head):")
display(prevloans_agg.head())
print("\nAggregated Previous Loans Data Info:")
prevloans_agg.info()

Aggregated Previous Loans Data (Head):

,customerid,num_prev_loans,total_prev_loanamount,avg_prev_loanamount,total_prev_totaldue,avg_prev_totaldue,avg_prev_termdays
0,8a1088a0484472eb01484669e3ce4e0b,1,10000.0,10000.000000,11500.0,11500.000000,15.000000
1,8a1a1e7e4f707f8b014f797718316cad,4,70000.0,17500.000000,89500.0,22375.000000,37.500000
2,8a1a32fc49b632520149c3b8fdf85139,7,90000.0,12857.142857,106500.0,15214.285714,19.285714
3,8a1eb5ba49a682300149c3c068b806c7,8,130000.0,16250.000000,162400.0,20300.000000,33.750000
4,8a1edbf14734127f0147356fdb1b1eb2,2,20000.0,10000.000000,24500.0,12250.000000,22.500000

Aggregated Previous Loans Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4359 entries, 0 to 4358
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customerid             4359 non-null   object
 1   num_prev_loans         4359 non-null   int64
 2   total_prev_loanamount  4359 non-null   float64
 3   avg_prev_loanamount    4359 non-null   float64
 4   total_prev_totaldue    4359 non-null   float64
 5   avg_prev_totaldue      4359 non-null   float64
 6   avg_prev_termdays      4359 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 238.5+ KB

Finally, merge the aggregated previous loans data (`prevloans_agg`) with the combined `train` dataset.

In [12]:
# Merge the aggregated previous loans with the main train dataframe
train = pd.merge(train, prevloans_agg, on='customerid', how='left')

print("\nFinal Merged Train Data (Head):")
display(train.head())
print("\nFinal Merged Train Data Info:")
train.info()
print("\nShape of the final train dataset:", train.shape)

Final Merged Train Data (Head):

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,...,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,num_prev_loans,total_prev_loanamount,avg_prev_loanamount,total_prev_totaldue,avg_prev_totaldue,avg_prev_termdays
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,NaN,Good,...,Diamond Bank,NaN,Permanent,Post-Graduate,11.0,200000.0,18181.818182,242900.0,22081.818182,30.0
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,NaN,Good,...,GT Bank,"DUGBE,IBADAN",Permanent,Graduate,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,NaN,Good,...,EcoBank,NaN,Permanent,NaN,6.0,60000.0,10000.000000,70500.0,11750.000000,17.5
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,NaN,Good,...,First Bank,NaN,Permanent,NaN,2.0,20000.0,10000.000000,24500.0,12250.000000,22.5
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,NaN,Good,...,GT Bank,NaN,Permanent,Primary,8.0,150000.0,18750.000000,188400.0,23550.000000,37.5

Final Merged Train Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   object
 4   creationdate                4376 non-null   object
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   object
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
 18  num_prev_loans              4367 non-null   float64
 19  total_prev_loanamount       4367 non-null   float64
 20  avg_prev_loanamount         4367 non-null   float64
 21  total_prev_totaldue         4367 non-null   float64
 22  avg_prev_totaldue           4367 non-null   float64
 23  avg_prev_termdays           4367 non-null   float64
dtypes: float64(10), int64(3), object(11)
memory usage: 820.6+ KB

Shape of the final train dataset: (4376, 24)

In [13]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   object
 4   creationdate                4376 non-null   object
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   object
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
 18  num_prev_loans              4367 non-null   float64
 19  total_prev_loanamount       4367 non-null   float64
 20  avg_prev_loanamount         4367 non-null   float64
 21  total_prev_totaldue         4367 non-null   float64
 22  avg_prev_totaldue           4367 non-null   float64
 23  avg_prev_termdays           4367 non-null   float64
dtypes: float64(10), int64(3), object(11)
memory usage: 820.6+ KB

In [14]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                1450 non-null   object
 4   creationdate                1450 non-null   object
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   num_prev_loans              1442 non-null   float64
 10  total_prev_loanamount       1442 non-null   float64
 11  avg_prev_loanamount         1442 non-null   float64
 12  total_prev_totaldue         1442 non-null   float64
 13  avg_prev_totaldue           1442 non-null   float64
 14  avg_prev_termdays           1442 non-null   float64
 15  birthdate                   385 non-null    object
 16  bank_account_type           385 non-null    object
 17  longitude_gps               385 non-null    float64
 18  latitude_gps                385 non-null    float64
 19  bank_name_clients           385 non-null    object
 20  bank_branch_clients         4 non-null      object
 21  employment_status_clients   332 non-null    object
 22  level_of_education_clients  47 non-null     object
dtypes: float64(9), int64(4), object(10)
memory usage: 260.7+ KB

In [15]:
sampsub = pd.read_csv('/content/loan_default_data/SampleSubmission.csv')
#sampsub.head()

In [16]:
test_id = test.drop(['customerid'], axis=1)
train_id = train.drop(['customerid', 'systemloanid'], axis=1)

test_is = test.drop(['systemloanid'], axis=1)

In [17]:
cat_cols = train.select_dtypes(include="object").columns
cat_cols = list(cat_cols)
print(cat_cols)

['customerid', 'approveddate', 'creationdate', 'referredby', 'good_bad_flag', 'birthdate', 'bank_account_type', 'bank_name_clients', 'bank_branch_clients', 'employment_status_clients', 'level_of_education_clients']

In [18]:
num_cols = test.select_dtypes(include="number").columns
num_cols = list(num_cols)
print(num_cols)

['systemloanid', 'loannumber', 'loanamount', 'totaldue', 'termdays', 'num_prev_loans', 'total_prev_loanamount', 'avg_prev_loanamount', 'total_prev_totaldue', 'avg_prev_totaldue', 'avg_prev_termdays', 'longitude_gps', 'latitude_gps']

In [19]:
# Select numeric columns dynamically
num_cols_train = train.select_dtypes(include=['int64', 'float64']).columns
num_cols_test = test.select_dtypes(include=['int64', 'float64']).columns

# Select categorical columns dynamically
cat_cols_train = train.select_dtypes(include='object').columns
cat_cols_test = test.select_dtypes(include='object').columns

# Fill missing values
train[num_cols_train] = train[num_cols_train].fillna(0)
test[num_cols_test] = test[num_cols_test].fillna(0)

train[cat_cols_train] = train[cat_cols_train].fillna('unknown')
test[cat_cols_test] = test[cat_cols_test].fillna('unknown')

In [20]:
# Convert to datetime
train['approveddate'] = pd.to_datetime(train['approveddate'], errors='coerce')
train['creationdate'] = pd.to_datetime(train['creationdate'], errors='coerce')

test['approveddate'] = pd.to_datetime(test['approveddate'], errors='coerce')
test['creationdate'] = pd.to_datetime(test['creationdate'], errors='coerce')

/tmp/ipython-input-1897446360.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test['approveddate'] = pd.to_datetime(test['approveddate'], errors='coerce')
/tmp/ipython-input-1897446360.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test['creationdate'] = pd.to_datetime(test['creationdate'], errors='coerce')

In [21]:
# Year, month, day, weekday
for df in [train, test]:
    df['approved_year'] = df['approveddate'].dt.year
    df['approved_month'] = df['approveddate'].dt.month
    df['approved_day'] = df['approveddate'].dt.day
    df['approved_weekday'] = df['approveddate'].dt.weekday  # 0=Monday, 6=Sunday

    # Loan age in days
    df['loan_age_days'] = (df['approveddate'] - df['creationdate']).dt.days
train = train.drop(['approveddate', 'creationdate'], axis=1)
test = test.drop(['approveddate', 'creationdate'], axis=1)
# Select numeric columns dynamically
num_cols_train = train.select_dtypes(include=['int64', 'float64']).columns
num_cols_test = test.select_dtypes(include=['int64', 'float64']).columns

# Select categorical columns dynamically
cat_cols_train = train.select_dtypes(include='object').columns
cat_cols_test = test.select_dtypes(include='object').columns

# Fill missing values
train[num_cols_train] = train[num_cols_train].fillna(0)
test[num_cols_test] = test[num_cols_test].fillna(0)

train[cat_cols_train] = train[cat_cols_train].fillna('unknown')
test[cat_cols_test] = test[cat_cols_test].fillna('unknown')
today = pd.Timestamp.today()
train['age'] = (today - pd.to_datetime(train['birthdate'], errors='coerce')).dt.days // 365
test['age'] = (today - pd.to_datetime(test['birthdate'], errors='coerce')).dt.days // 365

train.drop('birthdate', axis=1, inplace=True)
test.drop('birthdate', axis=1, inplace=True)

# Select numeric columns dynamically
num_cols_train = train.select_dtypes(include=['int64', 'float64']).columns
num_cols_test = test.select_dtypes(include=['int64', 'float64']).columns

# Select categorical columns dynamically
cat_cols_train = train.select_dtypes(include='object').columns
cat_cols_test = test.select_dtypes(include='object').columns

# Fill missing values
train[num_cols_train] = train[num_cols_train].fillna(0)
test[num_cols_test] = test[num_cols_test].fillna(0)

train[cat_cols_train] = train[cat_cols_train].fillna('unknown')
test[cat_cols_test] = test[cat_cols_test].fillna('unknown')


test_ids = test['customerid'].copy()

/tmp/ipython-input-3412906405.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test['age'] = (today - pd.to_datetime(test['birthdate'], errors='coerce')).dt.days // 365

In [22]:
# Target variable
# Check if 'good_bad_flag' exists before extracting and converting
if 'good_bad_flag' in train.columns:
    y = train['good_bad_flag'].map({'Bad': 0, 'Good': 1})
    # Drop 'good_bad_flag' from train now that y is set
    train = train.drop('good_bad_flag', axis=1)
else:
    print("Warning: 'good_bad_flag' column not found in 'train' DataFrame. Assuming 'y' is already set.")

# Drop other ID columns from train
cols_to_drop_train_ids = ['customerid', 'systemloanid']
for col in cols_to_drop_train_ids:
    if col in train.columns:
        train = train.drop(col, axis=1)

# Drop ID columns from test
cols_to_drop_test_ids = ['customerid', 'systemloanid']
for col in cols_to_drop_test_ids:
    if col in test.columns:
        test = test.drop(col, axis=1)

In [23]:
# Define the mapping for education
edu_map = {
    "No formal education": 0,
    "Primary education": 1,
    "Secondary education": 2,
    "Tertiary education": 3
}

# Encode train
train["education_num"] = train["level_of_education_clients"].map(edu_map).fillna(-1).astype(int)

# Encode test
test["education_num"] = test["level_of_education_clients"].map(edu_map).fillna(-1).astype(int)

# Drop the original categorical column
train = train.drop("level_of_education_clients", axis=1)
test = test.drop("level_of_education_clients", axis=1)

In [24]:
train["loanamount_per_age"] = train["loanamount"] / (train["age"] + 1)

test["loanamount_per_age"] = test["loanamount"] / (test["age"] + 1)

train["totaldue_per_age"] = train["totaldue"] / (train["age"] + 1)

test["totaldue_per_age"] = test["totaldue"] / (test["age"] + 1)

train["loanamount_per_age"].isna().sum()
test["loanamount_per_age"].isna().sum()

train["totaldue_per_age"].isna().sum()
test["totaldue_per_age"].isna().sum()

np.int64(0)

In [25]:
from sklearn.preprocessing import OrdinalEncoder

# --- Ordinal features ---
ordinal_cols = [ 'employment_status_clients']  # make sure 'education_num' already exists
train[ordinal_cols] = train[ordinal_cols].fillna(0)  # handle missing values
test[ordinal_cols] = test[ordinal_cols].fillna(0)

ord_enc = OrdinalEncoder()
train[ordinal_cols] = ord_enc.fit_transform(train[ordinal_cols])
test[ordinal_cols] = ord_enc.transform(test[ordinal_cols])

# --- One-hot features ---
onehot_cols = ['bank_account_type', 'bank_name_clients', 'bank_branch_clients', 'referredby']

# Fill missing values
train[onehot_cols] = train[onehot_cols].fillna('unknown')
test[onehot_cols] = test[onehot_cols].fillna('unknown')

# One-hot encoding
train = pd.get_dummies(train, columns=onehot_cols, prefix_sep="_")
test = pd.get_dummies(test, columns=onehot_cols, prefix_sep="_")

# --- Align train/test columns ---
train, test = train.align(test, join='left', axis=1, fill_value=0)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, y, test_size=0.2, random_state=42, stratify=y)

print("Training and validation sets created successfully.")
print(f"X_train shape: {X_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_val shape: {y_val.shape}")

Training and validation sets created successfully.
X_train shape: (3500, 599)
X_val shape: (876, 599)
y_train shape: (3500,)
y_val shape: (876,)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, y, test_size=0.2, random_state=42, stratify=y)

print("Training and validation sets created successfully.")
print(f"X_train shape: {X_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_val shape: {y_val.shape}")

Training and validation sets created successfully.
X_train shape: (3500, 599)
X_val shape: (876, 599)
y_train shape: (3500,)
y_val shape: (876,)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)


# Initialize StandardScaler
scaler = StandardScaler()

# Fit the scaler on X_train and transform both X_train and X_val
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [29]:
# Initialize and train the Logistic Regression model with scaled data
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)
print("Logistic Regression model initialized and trained successfully with scaled data.")
y_pred = model.predict(X_val_scaled)
y_prob = model.predict_proba(X_val_scaled)[:, 1]

Logistic Regression model initialized and trained successfully with scaled data.

In [30]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_val, y_pred)
error_rate = (1 - accuracy) * 100

print(f"Accuracy Score: {accuracy:.4f}")
print(f"Error Rate: {error_rate:.2f}%")

Accuracy Score: 0.7808
Error Rate: 21.92%

In [31]:
# Scale the test data using the same scaler fitted on the training data
X_test_scaled = scaler.transform(test)

# Make predictions on the scaled test data
y_test_pred = model.predict(X_test_scaled)
y_test_prob = model.predict_proba(X_test_scaled)[:, 1]

print("Predictions on the test set completed successfully.")
print("Sample of predicted classes (first 10):", y_test_pred[:10])
print("Sample of predicted probabilities for positive class (first 10):", y_test_prob[:10])

Predictions on the test set completed successfully.
Sample of predicted classes (first 10): [1 1 1 1 1 1 1 1 1 1]
Sample of predicted probabilities for positive class (first 10): [0.71236714 0.94014417 0.82885124 0.88046929 0.80538109 0.86922458
 0.77720428 0.74492679 0.81132665 0.97730465]

In [32]:
submission = pd.DataFrame({
    'customerID': test_ids,
    'Good_Bad_flag': y_test_pred
})

#submission.to_csv("submission.csv", index=False)

print("Submission preview:")
print(submission.head())

Submission preview:
                         customerID  Good_Bad_flag
0  8a858899538ddb8e015390510b321f08              1
1  8a858959537a097401537a4e316e25f7              1
2  8a8589c253ace09b0153af6ba58f1f31              1
3  8a858e095aae82b7015aae86ca1e030b              1
4  8a858e225a28c713015a30db5c48383d              1

# Task
Optimize the Logistic Regression model for loan default prediction by applying Recursive Feature Elimination (RFE) to select the most important numerical features, re-training the model on the refined feature set, and generating a submission file with the improved predictions. Also, summarize the performance improvement.

## Apply RFE Feature Selection

### Subtask:
Apply Recursive Feature Elimination (RFE) using a Logistic Regression estimator to select the most important features from the numerical training data. This will help reduce dimensionality and potentially improve model performance.

**Reasoning**:
To apply Recursive Feature Elimination, I need to import the necessary classes and initialize the RFE model with a Logistic Regression estimator, then fit it to the training data.

In [33]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Initialize a Logistic Regression model as the estimator for RFE
# Ensure max_iter and random_state match previous model parameters
estimator = LogisticRegression(max_iter=1000, random_state=42)

# Initialize RFE with the estimator, specifying n_features_to_select and step
# n_features_to_select is set to 50 as per instruction (or another appropriate number)
# step=1 means to remove one feature at each iteration
rfe_selector = RFE(estimator=estimator, n_features_to_select=50, step=1)

# Fit the RFE model to the training data
rfe_selector.fit(X_train_scaled, y_train)

print("RFE selector fitted successfully.")

RFE selector fitted successfully.

**Reasoning**:
Now that RFE has been fitted, I need to extract the selected features from the training, validation, and test datasets. This will create new datasets with only the most important features as determined by RFE.

In [34]:
X_train_selected = X_train_scaled[:, rfe_selector.support_]
X_val_selected = X_val_scaled[:, rfe_selector.support_]
X_test_selected = X_test_scaled[:, rfe_selector.support_]

print(f"Original X_train_scaled shape: {X_train_scaled.shape}")
print(f"X_train_selected shape: {X_train_selected.shape}")
print(f"Original X_val_scaled shape: {X_val_scaled.shape}")
print(f"X_val_selected shape: {X_val_selected.shape}")
print(f"Original X_test_scaled shape: {X_test_scaled.shape}")
print(f"X_test_selected shape: {X_test_selected.shape}")

Original X_train_scaled shape: (3500, 599)
X_train_selected shape: (3500, 50)
Original X_val_scaled shape: (876, 599)
X_val_selected shape: (876, 50)
Original X_test_scaled shape: (1450, 599)
X_test_selected shape: (1450, 50)

## Re-train the Model with Selected Features

### Subtask:
Re-train the Logistic Regression model using the features selected by RFE (`X_train_selected`, `X_val_selected`), and then evaluate its performance on the validation set.

**Reasoning**:
Now that the features have been selected using RFE, I need to re-initialize and train a new Logistic Regression model using only these selected features. This will allow for evaluation of the model's performance with the reduced feature set.

In [35]:
from sklearn.linear_model import LogisticRegression

# Initialize a new Logistic Regression model with the same parameters
model_rfe = LogisticRegression(max_iter=1000, random_state=42)

# Train the model using the RFE-selected scaled training data
model_rfe.fit(X_train_selected, y_train)

print("Logistic Regression model re-trained successfully with RFE-selected features.")

# Make predictions on the RFE-selected scaled validation data
y_pred_rfe = model_rfe.predict(X_val_selected)
y_prob_rfe = model_rfe.predict_proba(X_val_selected)[:, 1]

print("Predictions on validation set with RFE-selected features completed.")

Logistic Regression model re-trained successfully with RFE-selected features.
Predictions on validation set with RFE-selected features completed.

**Reasoning**:
To evaluate the performance of the Logistic Regression model after RFE feature selection, I need to calculate the accuracy score and error rate on the validation set, comparing it to the performance of the original model.

In [36]:
from sklearn.metrics import accuracy_score

accuracy_rfe = accuracy_score(y_val, y_pred_rfe)
error_rate_rfe = (1 - accuracy_rfe) * 100

print(f"Accuracy Score with RFE: {accuracy_rfe:.4f}")
print(f"Error Rate with RFE: {error_rate_rfe:.2f}%")

print("\n--- Comparison with Original Model ---")
print(f"Original Accuracy Score: {accuracy:.4f}")
print(f"Original Error Rate: {error_rate:.2f}%")

performance_summary = {
    "original_accuracy": accuracy,
    "original_error_rate": error_rate,
    "rfe_accuracy": accuracy_rfe,
    "rfe_error_rate": error_rate_rfe
}

Accuracy Score with RFE: 0.7808
Error Rate with RFE: 21.92%

--- Comparison with Original Model ---
Original Accuracy Score: 0.7808
Original Error Rate: 21.92%

**Reasoning**:
To complete the subtask of generating a submission file, I need to use the RFE-trained model (`model_rfe`) to make predictions on the RFE-selected test data (`X_test_selected`). These predictions will then be formatted into a submission DataFrame using the previously saved `test_ids`.

In [37]:
y_test_pred_rfe = model_rfe.predict(X_test_selected)
y_test_prob_rfe = model_rfe.predict_proba(X_test_selected)[:, 1]

submission_rfe = pd.DataFrame({
    'customerID': test_ids,
    'Good_Bad_flag': y_test_pred_rfe
})

print("Submission preview with RFE-selected features:")
print(submission_rfe.head())

# Save the submission file if needed
# submission_rfe.to_csv("submission_rfe.csv", index=False)
submission.to_csv("submission.csv", index=False)

Submission preview with RFE-selected features:
                         customerID  Good_Bad_flag
0  8a858899538ddb8e015390510b321f08              1
1  8a858959537a097401537a4e316e25f7              1
2  8a8589c253ace09b0153af6ba58f1f31              1
3  8a858e095aae82b7015aae86ca1e030b              1
4  8a858e225a28c713015a30db5c48383d              1

In [39]:
import pandas as pd

selected_features = X_train.columns[rfe_selector.support_]

# Get the coefficients from the re-trained Logistic Regression model
# For binary classification, coef_ is typically a 2D array, so we take the first (and only) row.
importances = model_rfe.coef_[0]

# Create a DataFrame to display feature importances
feature_importance_df = pd.DataFrame({
    'Feature': selected_features,
    'Coefficient': importances
})

# Sort by absolute coefficient value for importance
feature_importance_df['Abs_Coefficient'] = abs(feature_importance_df['Coefficient'])
feature_importance_df = feature_importance_df.sort_values(by='Abs_Coefficient', ascending=False)

print("Feature Importances (Coefficients) from RFE-selected Logistic Regression Model:")
print(feature_importance_df)

Feature Importances (Coefficients) from RFE-selected Logistic Regression Model:
                                        Feature  Coefficient  Abs_Coefficient
0                                    loanamount     0.795427         0.795427
7                            loanamount_per_age     0.698319         0.698319
8                              totaldue_per_age    -0.648620         0.648620
10                    bank_account_type_Savings    -0.520893         0.520893
4                           total_prev_totaldue    -0.446359         0.446359
16                  bank_branch_clients_unknown    -0.369620         0.369620
5                             avg_prev_totaldue     0.314447         0.314447
6                                           age     0.276263         0.276263
2                                      termdays    -0.275080         0.275080
3                     employment_status_clients    -0.254780         0.254780
1                                      totaldue    -0.245189         0.245189
21  referredby_8a858e125b391784015b395fa56243e6    -0.222109         0.222109
49                           referredby_unknown    -0.219200         0.219200
31  referredby_8a858edb552adcfd015531bdc5371d37    -0.210974         0.210974
9                       bank_account_type_Other    -0.206779         0.206779
23  referredby_8a858e2d5bb55d46015bc86b9e566836    -0.200833         0.200833
12        bank_branch_clients_ IDI - ORO MUSHIN    -0.198688         0.198688
14                bank_branch_clients_OJUELEGBA    -0.197417         0.197417
13                  bank_branch_clients_GBAGADA    -0.189118         0.189118
24  referredby_8a858e335b806e4d015b807c181d101f    -0.187268         0.187268
15        bank_branch_clients_WHARF ROAD, APAPA    -0.187149         0.187149
28  referredby_8a858e935b496584015b4a2c3e973ad3    -0.184716         0.184716
11                 bank_name_clients_Unity Bank     0.178080         0.178080
43  referredby_8a858f99560bbe45015613f9b9fa2171    -0.141518         0.141518
38  referredby_8a858f6e5b1a4fd0015b1a555f54042b    -0.139376         0.139376
22  referredby_8a858e255a423087015a466009d66e93    -0.138942         0.138942
44  referredby_8a858fa359d61dae0159d698bf503d29    -0.137500         0.137500
45  referredby_8a858fab5b9105dc015b999726de4412    -0.136844         0.136844
48  referredby_8a858fed5a3d7bb7015a3de90f6c297c    -0.136679         0.136679
42  referredby_8a858f8f5bfd3cfa015c026e474b47a5    -0.136058         0.136058
35  referredby_8a858f365b2547f3015b2bfd85c85ec1    -0.135757         0.135757
30  referredby_8a858ed45c454c11015c4e1307e35dd9    -0.135425         0.135425
29  referredby_8a858eb65b19b654015b19d9d5aa1ba1    -0.135420         0.135420
33  referredby_8a858efe5bca0a81015bcdaee15c0bb3    -0.135199         0.135199
18  referredby_8a85882653bc51f50153d00a923d26cb    -0.135189         0.135189
34  referredby_8a858f165b147438015b149b3acc1b44    -0.134895         0.134895
19  referredby_8a85884e54a0565b0154a05a7dd10159    -0.134792         0.134792
32  referredby_8a858ee758a4dfbc0158abd355eb4e87    -0.134557         0.134557
25  referredby_8a858e335c1122c5015c116f9bd31ef8    -0.134508         0.134508
41  referredby_8a858f7e5c69a6e3015c7abe2c1b37d3    -0.134144         0.134144
26  referredby_8a858e625c8d993a015c956a81de12f8    -0.134144         0.134144
27  referredby_8a858e875c63d395015c6c94a4246bf8    -0.134144         0.134144
47  referredby_8a858fea5b391cd7015b393aed9e2a04    -0.134052         0.134052
46  referredby_8a858fdf5bf85f71015bf93c8dd53cc7    -0.134011         0.134011
39  referredby_8a858f765a4e7c76015a5086a54e39cf    -0.133923         0.133923
17  referredby_8a85880353acff880153af354a6719df    -0.133682         0.133682
37  referredby_8a858f615591c2cc01559597a77202c6    -0.133542         0.133542
20  referredby_8a8589ec542eaa8901544d30b510384d    -0.133353         0.133353
36  referredby_8a858f495bcefdb9015bd28dd6a91ae3    -0.133339         0.133339
40  referredby_8a858f795896e56b0158a4eb84d1648d    -0.133073         0.133073

### Performance Improvement Summary

- **Original Model Accuracy**: 0.7808
- **Original Model Error Rate**: 21.92%

- **RFE Model Accuracy**: 0.7808
- **RFE Model Error Rate**: 21.92%

In this instance, applying RFE with `n_features_to_select=50` did not lead to a change in the accuracy score or error rate on the validation set compared to the full feature set. While accuracy remained the same, RFE successfully reduced the dimensionality of the feature space from 599 features to 50, which can lead to benefits such as faster training times and potentially better generalization on unseen data, even if the validation accuracy didn't immediately reflect an improvement.

### Performance Improvement Summary

- **Original Model Accuracy**: 0.7808
- **Original Model Error Rate**: 21.92%

- **RFE Model Accuracy**: 0.7808
- **RFE Model Error Rate**: 21.92%

In this instance, applying RFE with `n_features_to_select=50` did not lead to a change in the accuracy score or error rate on the validation set compared to the full feature set. While accuracy remained the same, RFE successfully reduced the dimensionality of the feature space from 599 features to 50, which can lead to benefits such as faster training times and potentially better generalization on unseen data, even if the validation accuracy didn't immediately reflect an improvement.

## Final Task

### Subtask:
Summarize the optimization process and the performance of the Logistic Regression model after applying RFE.

## Summary:

### Q&A
The optimization process involved applying Recursive Feature Elimination (RFE) to select the 50 most important features from the original 599 numerical features, using a Logistic Regression estimator. The model was then re-trained on this reduced feature set. After applying RFE, the Logistic Regression model achieved an accuracy of 0.7808 and an error rate of 21.92% on the validation set. This performance was identical to the original model's accuracy and error rate.

### Data Analysis Key Findings
*   Recursive Feature Elimination (RFE) successfully reduced the feature space from 599 to 50 features across the training, validation, and test datasets.
*   A Logistic Regression model re-trained on these 50 RFE-selected features achieved an accuracy of 0.7808 and an error rate of 21.92% on the validation set.
*   Compared to the original model, which also had an accuracy of 0.7808 and an error rate of 21.92%, RFE did not lead to an improvement in accuracy on the validation set for this specific configuration.
*   Despite no direct accuracy improvement, the model complexity was significantly reduced by using only 50 features instead of 599.

### Insights or Next Steps
*   While validation accuracy remained unchanged, the significant reduction in features (from 599 to 50) due to RFE is beneficial for model interpretability, reduced training time, and potential for better generalization on unseen data, even if not immediately reflected in validation accuracy.
*   To potentially improve performance, consider experimenting with different numbers of features to select (`n_features_to_select`) in RFE, or explore alternative feature selection techniques and hyperparameter tuning for the Logistic Regression model.

# Task
Apply Recursive Feature Elimination with Cross-Validation (RFECV) using a Logistic Regression estimator on the scaled training data (`X_train_scaled` and `y_train`) to find the optimal number of features.

## Apply RFECV for Optimal Feature Selection

### Subtask:
Apply Recursive Feature Elimination with Cross-Validation (RFECV) using a Logistic Regression estimator to identify the optimal number of features that yield the best performance, as determined by cross-validation. This will automatically select a more suitable number of features than a fixed 'n_features_to_select'.

**Reasoning**:
To perform Recursive Feature Elimination with Cross-Validation (RFECV) for optimal feature selection, I need to import the necessary classes, initialize the Logistic Regression estimator, and then initialize and fit the RFECV selector to the scaled training data. This will determine the optimal number of features.

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression

# Initialize a Logistic Regression model as the estimator for RFECV
estimator = LogisticRegression(max_iter=1000, random_state=42)

# Initialize RFECV with the estimator, specifying step and cross-validation folds
# scoring='accuracy' is a common choice for classification tasks
rfecv_selector = RFECV(estimator=estimator, step=1, cv=5, scoring='accuracy')

# Fit the RFECV model to the scaled training data
rfecv_selector.fit(X_train_scaled, y_train)

print("RFECV selector fitted successfully.")
print(f"Optimal number of features: {rfecv_selector.n_features_}")

RFECV selector fitted successfully.
Optimal number of features: 15

**Reasoning**:
Now that RFECV has been fitted and the optimal number of features identified, I need to extract these selected features from the scaled training, validation, and test datasets. This will create new datasets with only the most important features as determined by RFECV.

In [ ]:
X_train_rfecv = X_train_scaled[:, rfecv_selector.support_]
X_val_rfecv = X_val_scaled[:, rfecv_selector.support_]
X_test_rfecv = X_test_scaled[:, rfecv_selector.support_]

print(f"Original X_train_scaled shape: {X_train_scaled.shape}")
print(f"X_train_rfecv shape: {X_train_rfecv.shape}")
print(f"Original X_val_scaled shape: {X_val_scaled.shape}")
print(f"X_val_rfecv shape: {X_val_rfecv.shape}")
print(f"Original X_test_scaled shape: {X_test_scaled.shape}")
print(f"X_test_rfecv shape: {X_test_rfecv.shape}")

Original X_train_scaled shape: (3500, 599)
X_train_rfecv shape: (3500, 15)
Original X_val_scaled shape: (876, 599)
X_val_rfecv shape: (876, 15)
Original X_test_scaled shape: (1450, 599)
X_test_rfecv shape: (1450, 15)

## Re-scale Data with RFECV Selected Features

### Subtask:
Re-scale the features selected by RFECV. Fit a new StandardScaler on `X_train_rfecv` and then transform `X_train_rfecv`, `X_val_rfecv`, and `X_test_rfecv`.

**Reasoning**:
To ensure that the features are on a similar scale for the Logistic Regression model, I will re-scale the RFECV selected features using StandardScaler. This helps in preventing features with larger values from dominating the learning process.

In [ ]:
from sklearn.preprocessing import StandardScaler

# Initialize a new StandardScaler
scaler_rfecv = StandardScaler()

# Fit the scaler on X_train_rfecv and transform it
X_train_rfecv_scaled = scaler_rfecv.fit_transform(X_train_rfecv)

# Transform X_val_rfecv and X_test_rfecv using the fitted scaler
X_val_rfecv_scaled = scaler_rfecv.transform(X_val_rfecv)
X_test_rfecv_scaled = scaler_rfecv.transform(X_test_rfecv)

print("RFECV selected features successfully scaled.")
print(f"X_train_rfecv_scaled shape: {X_train_rfecv_scaled.shape}")
print(f"X_val_rfecv_scaled shape: {X_val_rfecv_scaled.shape}")
print(f"X_test_rfecv_scaled shape: {X_test_rfecv_scaled.shape}")

RFECV selected features successfully scaled.
X_train_rfecv_scaled shape: (3500, 15)
X_val_rfecv_scaled shape: (876, 15)
X_test_rfecv_scaled shape: (1450, 15)

In [ ]:
from sklearn.linear_model import LogisticRegression

# Initialize a new Logistic Regression model with the specified parameters
model_rfecv = LogisticRegression(max_iter=1000, random_state=42)

# Train the model using the RFECV-selected and re-scaled training data
model_rfecv.fit(X_train_rfecv_scaled, y_train)

print("Logistic Regression model re-trained successfully with RFECV-selected and re-scaled features.")

# Make predictions on the RFECV-selected and re-scaled validation data
y_pred_rfecv_scaled = model_rfecv.predict(X_val_rfecv_scaled)
y_prob_rfecv_scaled = model_rfecv.predict_proba(X_val_rfecv_scaled)[:, 1]

print("Predictions on validation set with RFECV-selected features completed.")

Logistic Regression model re-trained successfully with RFECV-selected and re-scaled features.
Predictions on validation set with RFECV-selected features completed.

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_rfecv_scaled = accuracy_score(y_val, y_pred_rfecv_scaled)
error_rate_rfecv_scaled = (1 - accuracy_rfecv_scaled) * 100

print(f"Accuracy Score with RFECV and scaled features: {accuracy_rfecv_scaled:.4f}")
print(f"Error Rate with RFECV and scaled features: {error_rate_rfecv_scaled:.2f}%")

print("\n--- Comparison with Original and RFE Model ---")
print(f"Original Model Accuracy: {performance_summary['original_accuracy']:.4f}")
print(f"Original Model Error Rate: {performance_summary['original_error_rate']:.2f}%")
print(f"RFE (fixed 50 features) Model Accuracy: {performance_summary['rfe_accuracy']:.4f}")
print(f"RFE (fixed 50 features) Model Error Rate: {performance_summary['rfe_error_rate']:.2f}%")

# Update performance summary with RFECV results
performance_summary["rfecv_accuracy"] = accuracy_rfecv_scaled
performance_summary["rfecv_error_rate"] = error_rate_rfecv_scaled

Accuracy Score with RFECV and scaled features: 0.7808
Error Rate with RFECV and scaled features: 21.92%

--- Comparison with Original and RFE Model ---
Original Model Accuracy: 0.7808
Original Model Error Rate: 21.92%
RFE (fixed 50 features) Model Accuracy: 0.7808
RFE (fixed 50 features) Model Error Rate: 21.92%

In [ ]:
y_test_pred_rfecv_scaled = model_rfecv.predict(X_test_rfecv_scaled)
y_test_prob_rfecv_scaled = model_rfecv.predict_proba(X_test_rfecv_scaled)[:, 1]

print("Predictions on the test set with RFECV-selected features completed successfully.")
print("Sample of predicted classes (first 10):", y_test_pred_rfecv_scaled[:10])
print("Sample of predicted probabilities for positive class (first 10):", y_test_prob_rfecv_scaled[:10])

Predictions on the test set with RFECV-selected features completed successfully.
Sample of predicted classes (first 10): [1 1 1 1 1 1 1 1 1 1]
Sample of predicted probabilities for positive class (first 10): [0.70197469 0.93415125 0.8105821  0.87729595 0.80592113 0.86796671
 0.81147229 0.73744771 0.80095034 0.89476623]

In [ ]:
submission_rfecv = pd.DataFrame({
    'customerID': test_ids,
    'Good_Bad_flag': y_test_pred_rfecv_scaled
})

print("Submission preview with RFECV-selected features:")
print(submission_rfecv.head())

Submission preview with RFECV-selected features:
                         customerID  Good_Bad_flag
0  8a858899538ddb8e015390510b321f08              1
1  8a858959537a097401537a4e316e25f7              1
2  8a8589c253ace09b0153af6ba58f1f31              1
3  8a858e095aae82b7015aae86ca1e030b              1
4  8a858e225a28c713015a30db5c48383d              1

In [ ]:
submission.to_csv("submission.csv", index=False)

In [ ]:
submission_rfecv.to_csv("submission_rfecv.csv", index=False)

print("Submission file 'submission_rfecv.csv' created successfully.")

Submission file 'submission_rfecv.csv' created successfully.

# Task
Optimize the Logistic Regression model for loan default prediction by performing hyperparameter tuning using GridSearchCV on the RFECV-selected and scaled training data. Evaluate the performance of the best tuned model on the validation set, generate a submission file with predictions on the test data, and finally, summarize the model's performance, comparing it to previous iterations (original and RFE-selected models).

## Hyperparameter Tuning with GridSearchCV

### Subtask:
Perform hyperparameter tuning for the Logistic Regression model using GridSearchCV on the RFECV-selected and scaled training data (X_train_rfecv_scaled, y_train). This will optimize parameters like 'C' (regularization strength) to find the best model configuration.

**Reasoning**:
To perform hyperparameter tuning, I need to import the necessary classes, define a parameter grid for the Logistic Regression model's 'C' parameter, initialize `GridSearchCV` with the estimator and grid, and then fit it to the RFECV-selected and scaled training data. Finally, I will print the best parameters and score found.

**Reasoning**:
The `NameError` indicates that `X_train_rfecv_scaled` was not defined in the current execution environment, likely due to previous cells not being executed or a kernel restart. To fix this, I need to ensure `X_train_rfecv_scaled` is available. This involves re-executing the steps for RFECV feature selection and subsequent scaling of those features. I will include the RFECV selection, feature extraction, and re-scaling steps before performing GridSearchCV to make the cell self-contained and resolve the `NameError`.

In [41]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFECV
from sklearn.preprocessing import StandardScaler

# Re-define estimator for RFECV (assuming it might have been lost or not run)
estimator = LogisticRegression(max_iter=1000, random_state=42)

# Re-fit RFECV selector to ensure rfecv_selector is defined and up-to-date
# (This code block is adapted from cell d6663c55 for robustness)
rfecv_selector = RFECV(estimator=estimator, step=1, cv=5, scoring='accuracy')
rfecv_selector.fit(X_train_scaled, y_train)

# Re-extract RFECV-selected features
# (This code block is adapted from cell 85fd9c2b for robustness)
X_train_rfecv = X_train_scaled[:, rfecv_selector.support_]
X_val_rfecv = X_val_scaled[:, rfecv_selector.support_]
X_test_rfecv = X_test_scaled[:, rfecv_selector.support_]

# Re-scale RFECV-selected features
# (This code block is adapted from cell 4290dd43 for robustness)
scaler_rfecv = StandardScaler()
X_train_rfecv_scaled = scaler_rfecv.fit_transform(X_train_rfecv)
X_val_rfecv_scaled = scaler_rfecv.transform(X_val_rfecv)
X_test_rfecv_scaled = scaler_rfecv.transform(X_test_rfecv)


# 2. Define a parameter grid for LogisticRegression
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100]
}

# 3. Initialize a LogisticRegression model as the estimator for GridSearchCV
logistic_model = LogisticRegression(max_iter=1000, random_state=42)

# 4. Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=logistic_model,
    param_grid=param_grid,
    cv=5,                 # 5-fold cross-validation
    scoring='accuracy',   # Metric to optimize
    n_jobs=-1,            # Use all available cores
    verbose=1
)

# 5. Fit the GridSearchCV object to the RFECV-selected and scaled training data
grid_search.fit(X_train_rfecv_scaled, y_train)

print("GridSearchCV completed successfully.")

# 6. Print the best parameters found
print(f"Best parameters found: {grid_search.best_params_}")

# 7. Print the best score achieved
print(f"Best cross-validation accuracy: {grid_search.best_score_:.4f}")

Fitting 5 folds for each of 6 candidates, totalling 30 fits
GridSearchCV completed successfully.
Best parameters found: {'C': 0.01}
Best cross-validation accuracy: 0.7831

**Reasoning**:
Now that GridSearchCV has identified the best hyperparameters, I need to evaluate the performance of this optimized model on the validation set. This involves getting the best estimator from `grid_search`, making predictions on `X_val_rfecv_scaled`, and then calculating the accuracy and error rate. I will also update the `performance_summary` dictionary.

**Reasoning**:
The `KeyError: 'rfecv_accuracy'` indicates that the `performance_summary` dictionary was not updated with the RFECV model's accuracy and error rate from the previous cell (`d438e2af`). To fix this, I need to ensure these values are calculated and added to `performance_summary` before attempting to print them in the current cell. I will re-calculate `accuracy_rfecv_scaled` and `error_rate_rfecv_scaled` and then update the `performance_summary` dictionary with these values within this cell.

**Reasoning**:
The `NameError` for `y_pred_rfecv_scaled` indicates that the predictions for the RFECV model on the validation set were not generated or were lost. To resolve this, I need to re-generate `y_pred_rfecv_scaled` and `y_prob_rfecv_scaled` using the `model_rfecv` and `X_val_rfecv_scaled` within this cell before attempting to access them. This will also ensure that the `performance_summary` dictionary is correctly updated with the RFECV model's metrics.

In [44]:
from sklearn.metrics import accuracy_score

# Get the best model from GridSearchCV
best_model_tuned = grid_search.best_estimator_

# Make predictions on the RFECV-selected and re-scaled validation data
y_pred_tuned = best_model_tuned.predict(X_val_rfecv_scaled)
y_prob_tuned = best_model_tuned.predict_proba(X_val_rfecv_scaled)[:, 1]

# Calculate accuracy and error rate for the tuned model
accuracy_tuned = accuracy_score(y_val, y_pred_tuned)
error_rate_tuned = (1 - accuracy_tuned) * 100

# --- Re-generate RFECV model predictions and metrics ---
# (This section is added to ensure y_pred_rfecv_scaled is defined and performance_summary is updated)

# Re-initialize the RFECV model (from previous step 024e1283) if it's not defined
# This is done defensively; ideally, model_rfecv should persist.
if 'model_rfecv' not in locals():
    from sklearn.linear_model import LogisticRegression
    model_rfecv = LogisticRegression(max_iter=1000, random_state=42)
    model_rfecv.fit(X_train_rfecv_scaled, y_train) # Re-fit if not already done

# Re-generate predictions for the RFECV model on the validation set
y_pred_rfecv_scaled = model_rfecv.predict(X_val_rfecv_scaled)
y_prob_rfecv_scaled = model_rfecv.predict_proba(X_val_rfecv_scaled)[:, 1]

# Re-calculate RFECV metrics and update performance_summary
accuracy_rfecv_scaled = accuracy_score(y_val, y_pred_rfecv_scaled)
error_rate_rfecv_scaled = (1 - accuracy_rfecv_scaled) * 100
performance_summary["rfecv_accuracy"] = accuracy_rfecv_scaled
performance_summary["rfecv_error_rate"] = error_rate_rfecv_scaled

# --- End of re-generation section ---

print(f"Accuracy Score with Tuned RFECV Model: {accuracy_tuned:.4f}")
print(f"Error Rate with Tuned RFECV Model: {error_rate_tuned:.2f}%")

print("\n--- Comparison with Previous Models ---")
print(f"Original Model Accuracy: {performance_summary['original_accuracy']:.4f}")
print(f"Original Model Error Rate: {performance_summary['original_error_rate']:.2f}%")
print(f"RFE (fixed 50 features) Model Accuracy: {performance_summary['rfe_accuracy']:.4f}")
print(f"RFE (fixed 50 features) Model Error Rate: {performance_summary['rfe_error_rate']:.2f}%")
print(f"RFECV (optimal features) Model Accuracy: {performance_summary['rfecv_accuracy']:.4f}")
print(f"RFECV (optimal features) Model Error Rate: {performance_summary['rfecv_error_rate']:.2f}%")

# Update performance summary with tuned RFECV results
performance_summary["tuned_rfecv_accuracy"] = accuracy_tuned
performance_summary["tuned_rfecv_error_rate"] = error_rate_tuned

Accuracy Score with Tuned RFECV Model: 0.7808
Error Rate with Tuned RFECV Model: 21.92%

--- Comparison with Previous Models ---
Original Model Accuracy: 0.7808
Original Model Error Rate: 21.92%
RFE (fixed 50 features) Model Accuracy: 0.7808
RFE (fixed 50 features) Model Error Rate: 21.92%
RFECV (optimal features) Model Accuracy: 0.7808
RFECV (optimal features) Model Error Rate: 21.92%

**Reasoning**:
To complete the task, I need to generate predictions on the test data using the best tuned model obtained from GridSearchCV. This involves using `best_model_tuned.predict` on `X_test_rfecv_scaled` and then creating a submission DataFrame with these predictions and the `test_ids`.

In [45]:
y_test_pred_tuned = best_model_tuned.predict(X_test_rfecv_scaled)
y_test_prob_tuned = best_model_tuned.predict_proba(X_test_rfecv_scaled)[:, 1]

submission_tuned = pd.DataFrame({
    'customerID': test_ids,
    'Good_Bad_flag': y_test_pred_tuned
})

print("Predictions on the test set with tuned RFECV features completed successfully.")
print("Sample of predicted classes (first 10):", y_test_pred_tuned[:10])
print("Sample of predicted probabilities for positive class (first 10):", y_test_prob_tuned[:10])

print("\nSubmission preview with tuned RFECV features:")
print(submission_tuned.head())

# Save the submission file
submission_tuned.to_csv("submission_tuned.csv", index=False)

Predictions on the test set with tuned RFECV features completed successfully.
Sample of predicted classes (first 10): [1 1 1 1 1 1 1 1 1 1]
Sample of predicted probabilities for positive class (first 10): [0.7243045  0.89443069 0.80457404 0.8491123  0.79724579 0.84786314
 0.78947515 0.76327412 0.79172685 0.84905683]

Submission preview with tuned RFECV features:
                         customerID  Good_Bad_flag
0  8a858899538ddb8e015390510b321f08              1
1  8a858959537a097401537a4e316e25f7              1
2  8a8589c253ace09b0153af6ba58f1f31              1
3  8a858e095aae82b7015aae86ca1e030b              1
4  8a858e225a28c713015a30db5c48383d              1

## Summary:

### Optimization Process
The optimization process involved a multi-stage approach:
1.  **Baseline Model**: A Logistic Regression model was initially trained on the full feature set to establish a baseline performance.
2.  **Recursive Feature Elimination (RFE)**: RFE with a Logistic Regression estimator was applied to select the 50 most important features. The model was re-trained on this reduced feature set.
3.  **Recursive Feature Elimination with Cross-Validation (RFECV)**: RFECV was used to automatically determine the optimal number of features (which was found to be 15) using 5-fold cross-validation. The model was then re-trained on these optimally selected features.
4.  **Hyperparameter Tuning with GridSearchCV**: Finally, GridSearchCV was employed to fine-tune the `C` parameter (regularization strength) of the Logistic Regression model using the RFECV-selected and scaled training data. This aimed to find the best `C` value for improved generalization.

### Model Performance Comparison
| Model Iteration           | Accuracy | Error Rate |
| :------------------------ | :------- | :--------- |
| Original Model            | 0.7808   | 21.92%     |
| RFE (50 features) Model   | 0.7808   | 21.92%     |
| RFECV (15 features) Model | 0.7808   | 21.92%     |
| Tuned RFECV Model         | 0.7808   | 21.92%     |

### Analysis of Performance
In this particular case, despite employing various feature selection and hyperparameter tuning techniques (RFE, RFECV, GridSearchCV), the validation accuracy and error rate of the Logistic Regression model remained consistent across all iterations at 0.7808 and 21.92%, respectively. This suggests:

*   **Robust Baseline**: The initial Logistic Regression model on the full feature set already achieved a performance level that was difficult to improve upon with these specific optimization methods and parameters on the validation set.
*   **Feature Redundancy/Impact**: While RFE and RFECV successfully reduced the dimensionality of the feature space (from 599 to 50, then to 15 features), this reduction did not translate into a direct improvement in predictive accuracy on the validation set. It's possible that the removed features, while numerous, did not contain much unique predictive signal beyond what was already captured by the selected features, or the remaining features were sufficiently informative.
*   **Regularization**: The hyperparameter tuning of the `C` parameter also did not yield a performance increase, indicating that the default or initial regularization strength was already suitable, or that the model is not highly sensitive to this parameter within the tested range for this dataset.

### Insights or Next Steps
*   **Model Complexity vs. Performance**: The primary benefit observed from RFE and RFECV is the significant reduction in model complexity and feature space (from 599 to just 15 features in the RFECV-tuned model). This can lead to faster training and inference times, improved model interpretability, and potentially better generalization on completely unseen data (outside the current validation set) by mitigating overfitting.
*   **Explore Other Models**: Given the consistent performance, it would be beneficial to experiment with more complex models (e.g., Gradient Boosting, Random Forests, Neural Networks) that might be able to capture more intricate patterns in the data.
*   **Advanced Feature Engineering**: Further feature engineering, potentially creating more complex interaction terms or domain-specific features, could unlock higher predictive power.
*   **Alternative Feature Selection**: Investigate other feature selection methods (e.g., tree-based feature importances, L1 regularization with different strengths) to see if a different subset of features yields better results.
*   **Cross-Validation Strategy**: Ensure the cross-validation strategy used throughout is robust and representative of the data distribution, especially for the original Logistic Regression setup.

## Final Task

### Subtask:
Summarize the performance of the hyperparameter-tuned model, comparing its accuracy and error rate with the previously trained models (original and RFE-selected fixed 50 features), and discuss the overall optimization and generalization achieved.

## Summary:

### Q&A
The hyperparameter-tuned Logistic Regression model, despite feature selection and tuning, achieved a validation accuracy of 0.7808 with an error rate of 21.92%. This performance is identical to the original model, the RFE (50 features) model, and the RFECV (15 features) model. While the accuracy did not improve, the model's complexity was significantly reduced by using only 15 features (down from 599), maintaining the same predictive power on the validation set. This suggests a robust baseline and that further optimization with these specific methods did not yield direct accuracy gains on the validation set.

### Data Analysis Key Findings
*   The hyperparameter tuning using GridSearchCV identified `C = 0.01` as the best parameter for the Logistic Regression model, achieving a best cross-validation accuracy of 0.7831.
*   The validation accuracy of the tuned RFECV model was 0.7808, with an error rate of 21.92%.
*   This performance remained consistent across all model iterations: the original model (accuracy: 0.7808, error rate: 21.92%), the RFE (50 features) model (accuracy: 0.7808, error rate: 21.92%), the RFECV (15 features) model (accuracy: 0.7808, error rate: 21.92%), and the final tuned RFECV model.
*   The RFECV process successfully reduced the number of features from 599 to an optimal 15, significantly decreasing model complexity without compromising validation accuracy.
*   Predictions for the test dataset were successfully generated using the best-tuned model, and a submission file (`submission_tuned.csv`) was created.

### Insights or Next Steps
*   Although validation accuracy did not improve, the significant reduction in feature space from 599 to 15 features implies improved model interpretability and potentially faster training/inference times, which are valuable benefits for deployment.
*   Since various feature selection and hyperparameter tuning methods did not enhance accuracy, exploring more complex machine learning models (e.g., Gradient Boosting, Random Forests) or advanced feature engineering techniques could be beneficial to potentially uncover more intricate patterns and improve predictive performance.

# Task
Create new advanced features for both the 'train' and 'test' DataFrames, such as interaction terms (e.g., `loanamount * termdays`) and ratio features (e.g., `totaldue / loanamount`).

## Advanced Feature Engineering

### Subtask:
Create new advanced features for both the 'train' and 'test' DataFrames, such as interaction terms (e.g., loanamount * termdays) and ratio features (e.g., totaldue / loanamount), to potentially uncover more complex patterns.

**Reasoning**:
I will create the specified interaction and ratio features for both the 'train' and 'test' DataFrames, ensuring to handle potential division-by-zero or NaN issues for the ratio features.

In [46]:
import numpy as np

for df_name, df in zip(['train', 'test'], [train, test]):
    # 1. Create interaction features
    df[f'loanamount_termdays_interaction'] = df['loanamount'] * df['termdays']
    df[f'loanamount_num_prev_loans_interaction'] = df['loanamount'] * df['num_prev_loans']

    # 2. Create ratio features
    # totaldue / loanamount
    df[f'totaldue_loanamount_ratio'] = df['totaldue'] / df['loanamount']
    df[f'totaldue_loanamount_ratio'].replace([np.inf, -np.inf], 0, inplace=True)
    df[f'totaldue_loanamount_ratio'].fillna(0, inplace=True)

    # total_prev_totaldue / total_prev_loanamount
    df[f'total_prev_due_loanamount_ratio'] = df['total_prev_totaldue'] / df['total_prev_loanamount']
    df[f'total_prev_due_loanamount_ratio'].replace([np.inf, -np.inf], 0, inplace=True)
    df[f'total_prev_due_loanamount_ratio'].fillna(0, inplace=True)

print("Advanced features created successfully for both train and test DataFrames.")
print("Train DataFrame new features head:")
print(train[['loanamount_termdays_interaction', 'loanamount_num_prev_loans_interaction', 'totaldue_loanamount_ratio', 'total_prev_due_loanamount_ratio']].head())
print("\nTest DataFrame new features head:")
print(test[['loanamount_termdays_interaction', 'loanamount_num_prev_loans_interaction', 'totaldue_loanamount_ratio', 'total_prev_due_loanamount_ratio']].head())

Advanced features created successfully for both train and test DataFrames.
Train DataFrame new features head:
   loanamount_termdays_interaction  loanamount_num_prev_loans_interaction  \
0                         900000.0                               330000.0
1                         450000.0                                    0.0
2                         300000.0                               120000.0
3                         150000.0                                20000.0
4                        1200000.0                               320000.0

   totaldue_loanamount_ratio  total_prev_due_loanamount_ratio
0                     1.1500                           1.2145
1                     1.1500                           0.0000
2                     1.1125                           1.1750
3                     1.1500                           1.2250
4                     1.1000                           1.2560

Test DataFrame new features head:
   loanamount_termdays_interaction  loanamount_num_prev_loans_interaction  \
0                           300000                                30000.0
1                          1200000                               360000.0
2                           600000                               100000.0
3                           900000                               210000.0
4                           600000                                60000.0

   totaldue_loanamount_ratio  total_prev_due_loanamount_ratio
0                      1.225                         1.265385
1                      1.100                         1.155349
2                      1.225                         1.225769
3                      1.150                         1.128333
4                      1.225                         1.250000

/tmp/ipython-input-2148970350.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'totaldue_loanamount_ratio'].replace([np.inf, -np.inf], 0, inplace=True)
/tmp/ipython-input-2148970350.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'totaldue_loanamount_ratio'].fillna(0, inplace=True)
/tmp/ipython-input-2148970350.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'total_prev_due_loanamount_ratio'].replace([np.inf, -np.inf], 0, inplace=True)
/tmp/ipython-input-2148970350.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'total_prev_due_loanamount_ratio'].fillna(0, inplace=True)
/tmp/ipython-input-2148970350.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'totaldue_loanamount_ratio'].replace([np.inf, -np.inf], 0, inplace=True)
/tmp/ipython-input-2148970350.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'totaldue_loanamount_ratio'].fillna(0, inplace=True)
/tmp/ipython-input-2148970350.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'total_prev_due_loanamount_ratio'].replace([np.inf, -np.inf], 0, inplace=True)
/tmp/ipython-input-2148970350.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[f'total_prev_due_loanamount_ratio'].fillna(0, inplace=True)

**Reasoning**:
The previous code generated `FutureWarning` due to chained assignments with `inplace=True`. While the code ran, it's better practice to assign the results back to the DataFrame explicitly to avoid potential issues in future pandas versions.

In [47]:
import numpy as np

for df_name, df in zip(['train', 'test'], [train, test]):
    # 1. Create interaction features
    df[f'loanamount_termdays_interaction'] = df['loanamount'] * df['termdays']
    df[f'loanamount_num_prev_loans_interaction'] = df['loanamount'] * df['num_prev_loans']

    # 2. Create ratio features
    # totaldue / loanamount
    df[f'totaldue_loanamount_ratio'] = df['totaldue'] / df['loanamount']
    df[f'totaldue_loanamount_ratio'] = df[f'totaldue_loanamount_ratio'].replace([np.inf, -np.inf], 0)
    df[f'totaldue_loanamount_ratio'] = df[f'totaldue_loanamount_ratio'].fillna(0)

    # total_prev_totaldue / total_prev_loanamount
    df[f'total_prev_due_loanamount_ratio'] = df['total_prev_totaldue'] / df['total_prev_loanamount']
    df[f'total_prev_due_loanamount_ratio'] = df[f'total_prev_due_loanamount_ratio'].replace([np.inf, -np.inf], 0)
    df[f'total_prev_due_loanamount_ratio'] = df[f'total_prev_due_loanamount_ratio'].fillna(0)

print("Advanced features created successfully for both train and test DataFrames.")
print("Train DataFrame new features head:")
print(train[['loanamount_termdays_interaction', 'loanamount_num_prev_loans_interaction', 'totaldue_loanamount_ratio', 'total_prev_due_loanamount_ratio']].head())
print("\nTest DataFrame new features head:")
print(test[['loanamount_termdays_interaction', 'loanamount_num_prev_loans_interaction', 'totaldue_loanamount_ratio', 'total_prev_due_loanamount_ratio']].head())

Advanced features created successfully for both train and test DataFrames.
Train DataFrame new features head:
   loanamount_termdays_interaction  loanamount_num_prev_loans_interaction  \
0                         900000.0                               330000.0
1                         450000.0                                    0.0
2                         300000.0                               120000.0
3                         150000.0                                20000.0
4                        1200000.0                               320000.0

   totaldue_loanamount_ratio  total_prev_due_loanamount_ratio
0                     1.1500                           1.2145
1                     1.1500                           0.0000
2                     1.1125                           1.1750
3                     1.1500                           1.2250
4                     1.1000                           1.2560

Test DataFrame new features head:
   loanamount_termdays_interaction  loanamount_num_prev_loans_interaction  \
0                           300000                                30000.0
1                          1200000                               360000.0
2                           600000                               100000.0
3                           900000                               210000.0
4                           600000                                60000.0

   totaldue_loanamount_ratio  total_prev_due_loanamount_ratio
0                      1.225                         1.265385
1                      1.100                         1.155349
2                      1.225                         1.225769
3                      1.150                         1.128333
4                      1.225                         1.250000

## Re-split and Re-scale Data

### Subtask:
Split the enhanced 'train' DataFrame into new training and validation sets. Then, scale these new feature sets and the 'test' set using StandardScaler to prepare them for the Random Forest model.

**Reasoning**:
To prepare the data for the Random Forest model, I need to split the enhanced 'train' DataFrame into new training and validation sets and then apply StandardScaler to these sets and the 'test' DataFrame.

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Split the 'train' DataFrame into training and validation sets
X_train_new, X_val_new, y_train_new, y_val_new = train_test_split(
    train, y, test_size=0.2, random_state=42, stratify=y
)

print("New training and validation sets created successfully.")
print(f"X_train_new shape: {X_train_new.shape}")
print(f"X_val_new shape: {X_val_new.shape}")
print(f"y_train_new shape: {y_train_new.shape}")
print(f"y_val_new shape: {y_val_new.shape}")

# 2. Initialize a StandardScaler object
scaler_new = StandardScaler()

# 3. Fit the scaler on X_train_new and transform both X_train_new and X_val_new
X_train_scaled_new = scaler_new.fit_transform(X_train_new)
X_val_scaled_new = scaler_new.transform(X_val_new)

print("\nNew training and validation feature sets scaled successfully.")
print(f"X_train_scaled_new shape: {X_train_scaled_new.shape}")
print(f"X_val_scaled_new shape: {X_val_scaled_new.shape}")

# 4. Transform the 'test' DataFrame using the same fitted StandardScaler
X_test_scaled_new = scaler_new.transform(test)

print("\nTest DataFrame scaled successfully.")
print(f"X_test_scaled_new shape: {X_test_scaled_new.shape}")

New training and validation sets created successfully.
X_train_new shape: (3500, 603)
X_val_new shape: (876, 603)
y_train_new shape: (3500,)
y_val_new shape: (876,)

New training and validation feature sets scaled successfully.
X_train_scaled_new shape: (3500, 603)
X_val_scaled_new shape: (876, 603)

Test DataFrame scaled successfully.
X_test_scaled_new shape: (1450, 603)

## Train Initial Random Forest Model

### Subtask:
Initialize and train a RandomForestClassifier on the scaled training data (X_train_scaled_new) and evaluate its performance on the scaled validation set (X_val_scaled_new).

**Reasoning**:
To initialize and train a RandomForestClassifier, and evaluate its performance on the validation set, I need to import the necessary classes, train the model, make predictions, calculate accuracy, and store the results.

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 1. Initialize a RandomForestClassifier object
# Set random_state for reproducibility and n_estimators (e.g., 100)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

# 2. Train the RandomForestClassifier model
rf_model.fit(X_train_scaled_new, y_train_new)

print("RandomForestClassifier model trained successfully.")

# 3. Make predictions on the X_val_scaled_new validation set
y_pred_rf = rf_model.predict(X_val_scaled_new)
y_prob_rf = rf_model.predict_proba(X_val_scaled_new)[:, 1]

print("Predictions on validation set completed.")

# 4. Calculate the accuracy score and error rate
accuracy_rf = accuracy_score(y_val_new, y_pred_rf)
error_rate_rf = (1 - accuracy_rf) * 100

# 5. Print the accuracy score and error rate
print(f"\nInitial Random Forest Model Accuracy: {accuracy_rf:.4f}")
print(f"Initial Random Forest Model Error Rate: {error_rate_rf:.2f}%")

# 6. Store these performance metrics in the performance_summary dictionary
performance_summary["initial_rf_accuracy"] = accuracy_rf
performance_summary["initial_rf_error_rate"] = error_rate_rf

print("Performance metrics stored in performance_summary.")

RandomForestClassifier model trained successfully.
Predictions on validation set completed.

Initial Random Forest Model Accuracy: 0.7614
Initial Random Forest Model Error Rate: 23.86%
Performance metrics stored in performance_summary.

## Hyperparameter Tuning for Random Forest

### Subtask:
Perform hyperparameter tuning for the RandomForestClassifier using GridSearchCV on the scaled training data to find the optimal set of parameters for improved performance.

**Reasoning**:
To perform hyperparameter tuning for the RandomForestClassifier, I need to import `GridSearchCV`, define a parameter grid for relevant hyperparameters, initialize the RandomForestClassifier as the estimator, and then fit GridSearchCV to the scaled training data.

In [50]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# 1. Define a parameter grid for RandomForestClassifier
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}

# 2. Initialize a RandomForestClassifier model as the estimator for GridSearchCV
rf_estimator = RandomForestClassifier(random_state=42, n_jobs=-1)

# 3. Initialize GridSearchCV
grid_search_rf = GridSearchCV(
    estimator=rf_estimator,
    param_grid=param_grid_rf,
    cv=5,                 # 5-fold cross-validation
    scoring='accuracy',   # Metric to optimize
    n_jobs=-1,            # Use all available cores
    verbose=1
)

# 4. Fit the GridSearchCV object to the scaled training data
grid_search_rf.fit(X_train_scaled_new, y_train_new)

print("GridSearchCV for Random Forest completed successfully.")

# 5. Print the best parameters found
print(f"Best parameters found for Random Forest: {grid_search_rf.best_params_}")

# 6. Print the best cross-validation score achieved
print(f"Best cross-validation accuracy for Random Forest: {grid_search_rf.best_score_:.4f}")

Fitting 5 folds for each of 27 candidates, totalling 135 fits
GridSearchCV for Random Forest completed successfully.
Best parameters found for Random Forest: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}
Best cross-validation accuracy for Random Forest: 0.7823

## Evaluate Tuned Random Forest Model

### Subtask:
Evaluate the performance of the best tuned RandomForestClassifier on the scaled validation set, comparing its accuracy and error rate to previous models.

**Reasoning**:
To evaluate the performance of the tuned Random Forest model, I will retrieve the best estimator from GridSearchCV, make predictions on the validation set, calculate accuracy and error rate, and then compare it to the performance of previous models and store the results.

In [51]:
from sklearn.metrics import accuracy_score

# 1. Get the best estimator from GridSearchCV for Random Forest
best_rf_model_tuned = grid_search_rf.best_estimator_

# 2. Make predictions on the scaled validation data using the best estimator
y_pred_rf_tuned = best_rf_model_tuned.predict(X_val_scaled_new)
y_prob_rf_tuned = best_rf_model_tuned.predict_proba(X_val_scaled_new)[:, 1]

# 3. Calculate the accuracy score for these predictions
accuracy_rf_tuned = accuracy_score(y_val_new, y_pred_rf_tuned)

# 4. Calculate the error rate
error_rate_rf_tuned = (1 - accuracy_rf_tuned) * 100

# 5. Print the accuracy score and error rate of the tuned Random Forest model
print(f"\nTuned Random Forest Model Accuracy: {accuracy_rf_tuned:.4f}")
print(f"Tuned Random Forest Model Error Rate: {error_rate_rf_tuned:.2f}%")

# 6. Print a comparison with previous models
print("\n--- Comparison with Previous Models ---")
print(f"Original Logistic Regression Model Accuracy: {performance_summary['original_accuracy']:.4f}")
print(f"Original Logistic Regression Model Error Rate: {performance_summary['original_error_rate']:.2f}%")
print(f"RFE Logistic Regression Model Accuracy: {performance_summary['rfe_accuracy']:.4f}")
print(f"RFE Logistic Regression Model Error Rate: {performance_summary['rfe_error_rate']:.2f}%")
print(f"RFECV Logistic Regression Model Accuracy: {performance_summary['rfecv_accuracy']:.4f}")
print(f"RFECV Logistic Regression Model Error Rate: {performance_summary['rfecv_error_rate']:.2f}%")
print(f"Tuned RFECV Logistic Regression Model Accuracy: {performance_summary['tuned_rfecv_accuracy']:.4f}")
print(f"Tuned RFECV Logistic Regression Model Error Rate: {performance_summary['tuned_rfecv_error_rate']:.2f}%")
print(f"Initial Random Forest Model Accuracy: {performance_summary['initial_rf_accuracy']:.4f}")
print(f"Initial Random Forest Model Error Rate: {performance_summary['initial_rf_error_rate']:.2f}%")

# 7. Store the accuracy and error rate of the tuned Random Forest model
performance_summary['tuned_rf_accuracy'] = accuracy_rf_tuned
performance_summary['tuned_rf_error_rate'] = error_rate_rf_tuned

print("\nPerformance metrics for tuned Random Forest stored in performance_summary.")

Tuned Random Forest Model Accuracy: 0.7820
Tuned Random Forest Model Error Rate: 21.80%

--- Comparison with Previous Models ---
Original Logistic Regression Model Accuracy: 0.7808
Original Logistic Regression Model Error Rate: 21.92%
RFE Logistic Regression Model Accuracy: 0.7808
RFE Logistic Regression Model Error Rate: 21.92%
RFECV Logistic Regression Model Accuracy: 0.7808
RFECV Logistic Regression Model Error Rate: 21.92%
Tuned RFECV Logistic Regression Model Accuracy: 0.7808
Tuned RFECV Logistic Regression Model Error Rate: 21.92%
Initial Random Forest Model Accuracy: 0.7614
Initial Random Forest Model Error Rate: 23.86%

Performance metrics for tuned Random Forest stored in performance_summary.

## Generate Random Forest Submission File

### Subtask:
Use the best hyperparameter-tuned RandomForestClassifier to make predictions on the scaled test data and create a submission file.

**Reasoning**:
To complete the subtask, I need to use the `best_rf_model_tuned` to make predictions on the `X_test_scaled_new` data, then assemble these predictions into a submission DataFrame, preview it, and save it to a CSV file.

In [52]:
y_test_pred_rf_tuned = best_rf_model_tuned.predict(X_test_scaled_new)
y_test_prob_rf_tuned = best_rf_model_tuned.predict_proba(X_test_scaled_new)[:, 1]

submission_rf_tuned = pd.DataFrame({
    'customerID': test_ids,
    'Good_Bad_flag': y_test_pred_rf_tuned
})

print("Predictions on the test set with tuned Random Forest completed successfully.")
print("Sample of predicted classes (first 10):", y_test_pred_rf_tuned[:10])
print("Sample of predicted probabilities for positive class (first 10):", y_test_prob_rf_tuned[:10])

print("\nSubmission preview with tuned Random Forest features:")
print(submission_rf_tuned.head())

submission_rf_tuned.to_csv("submission_rf_tuned.csv", index=False)
print("\nSubmission file 'submission_rf_tuned.csv' created successfully.")

Predictions on the test set with tuned Random Forest completed successfully.
Sample of predicted classes (first 10): [1 1 1 1 1 1 1 1 1 1]
Sample of predicted probabilities for positive class (first 10): [0.72313193 0.89761185 0.87743484 0.86345823 0.81353678 0.85622115
 0.70573092 0.67490065 0.79702004 0.86350992]

Submission preview with tuned Random Forest features:
                         customerID  Good_Bad_flag
0  8a858899538ddb8e015390510b321f08              1
1  8a858959537a097401537a4e316e25f7              1
2  8a8589c253ace09b0153af6ba58f1f31              1
3  8a858e095aae82b7015aae86ca1e030b              1
4  8a858e225a28c713015a30db5c48383d              1

Submission file 'submission_rf_tuned.csv' created successfully.

## Final Summary

### Subtask:
Summarize the entire optimization process, detailing the impact of advanced feature engineering and the Random Forest model. Compare its final performance to all previous Logistic Regression iterations and discuss overall improvements or insights.

## Summary:

### Data Analysis Key Findings

*   **Advanced Feature Engineering**: New interaction features (`loanamount_termdays_interaction`, `loanamount_num_prev_loans_interaction`) and ratio features (`totaldue_loanamount_ratio`, `total_prev_due_loanamount_ratio`) were successfully created for both the `train` and `test` DataFrames. Division by zero and `NaN` values for ratio features were handled by replacing them with 0.
*   **Data Preparation**: The enhanced `train` DataFrame was split into new training (3500 samples) and validation (876 samples) sets, and all feature sets (training, validation, and test) were successfully scaled using `StandardScaler`.
*   **Initial Random Forest Performance**: The initial `RandomForestClassifier` achieved an accuracy of 0.7614 on the validation set, with an error rate of 23.86%.
*   **Hyperparameter Tuning**: `GridSearchCV` identified optimal hyperparameters for the `RandomForestClassifier` as `{'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}`, resulting in a best cross-validation accuracy of 0.7823.
*   **Tuned Random Forest Performance**: The hyperparameter-tuned `RandomForestClassifier` achieved an accuracy of 0.7820 on the validation set, with an error rate of 21.80%. This marks a notable improvement over the initial Random Forest model's 0.7614 accuracy.
*   **Model Comparison**: The tuned Random Forest model (accuracy: 0.7820) performed marginally better than all previous Logistic Regression iterations (which consistently showed an accuracy of 0.7808) and significantly outperformed the initial Random Forest model.
*   **Submission File Generation**: Predictions were successfully made on the scaled test data using the tuned Random Forest model, and a submission file named `submission_rf_tuned.csv` was generated.

### Insights or Next Steps

*   The implementation of advanced feature engineering combined with a `RandomForestClassifier` and hyperparameter tuning led to a slight but consistent improvement in model performance compared to previous Logistic Regression models, indicating the value of exploring more complex features and non-linear models.
*   Further improvements could explore additional feature engineering (e.g., time-based features, principal component analysis), different ensemble methods (e.g., Gradient Boosting), or advanced neural network architectures, potentially coupled with more extensive hyperparameter optimization or ensemble techniques.